INSERT INTO banco(id, codigo, nome)VALUES(1,654,'A. J. RENNER');
INSERT INTO banco(id, codigo, nome)VALUES(2,246,'ABC - BRASIL');
INSERT INTO banco(id, codigo, nome)VALUES(3,025,'ALFA');
INSERT INTO banco(id, codigo, nome)VALUES(4,003,'AMAZÔNIA - BASA');
INSERT INTO banco(id, codigo, nome)VALUES(5,213,'ARBI');
INSERT INTO banco(id, codigo, nome)VALUES(6,019,'AZTECA');
INSERT INTO banco(id, codigo, nome)VALUES(7,096,'BANCO BMFBOVESPA');
INSERT INTO banco(id, codigo, nome)VALUES(8,719,'BANIF');
INSERT INTO banco(id, codigo, nome)VALUES(9,755,'BANK OF AMERICA MERRILL LYNCH');
INSERT INTO banco(id, codigo, nome)VALUES(10,740,'BARCLAYS');
INSERT INTO banco(id, codigo, nome)VALUES(11,107,'BBM');
INSERT INTO banco(id, codigo, nome)VALUES(12,081,'BBN BANCO BRASILEIRO DE NEGÓCIOS');
INSERT INTO banco(id, codigo, nome)VALUES(13,250,'BCV');
INSERT INTO banco(id, codigo, nome)VALUES(14,122,'BERJ');
INSERT INTO banco(id, codigo, nome)VALUES(15,739,'BGN');
INSERT INTO banco(id, codigo, nome)VALUES(16,078,'BI BES - ESPIRITO SANTO');
INSERT INTO banco(id, codigo, nome)VALUES(17,318,'BMG');
INSERT INTO banco(id, codigo, nome)VALUES(18,004,'BNB');
INSERT INTO banco(id, codigo, nome)VALUES(19,752,'BNP PARIBAS BRASIL');
INSERT INTO banco(id, codigo, nome)VALUES(20,017,'BNY MELLON');
INSERT INTO banco(id, codigo, nome)VALUES(21,248,'BOAVISTA INTERATLÂNTICO');
INSERT INTO banco(id, codigo, nome)VALUES(22,218,'BONSUCESSO');
INSERT INTO banco(id, codigo, nome)VALUES(23,069,'BPN BRASIL');
INSERT INTO banco(id, codigo, nome)VALUES(24,065,'BRACCE');
INSERT INTO banco(id, codigo, nome)VALUES(25,063,'BRADESCARD');
INSERT INTO banco(id, codigo, nome)VALUES(26,237,'BRADESCO');
INSERT INTO banco(id, codigo, nome)VALUES(27,036,'BRADESCO BBI');
INSERT INTO banco(id, codigo, nome)VALUES(28,204,'BRADESCO CARTÕES');
INSERT INTO banco(id, codigo, nome)VALUES(29,394,'BRADESCO FINANCIAMENTOS');
INSERT INTO banco(id, codigo, nome)VALUES(30,225,'BRASCAN');
INSERT INTO banco(id, codigo, nome)VALUES(31,001,'BRASIL');
INSERT INTO banco(id, codigo, nome)VALUES(32,125,'BRASIL PLURAL');
INSERT INTO banco(id, codigo, nome)VALUES(33,070,'BRB - BCO. BRASÍLIA');
INSERT INTO banco(id, codigo, nome)VALUES(34,208,'BTG PACTUAL');
INSERT INTO banco(id, codigo, nome)VALUES(35,263,'CACIQUE');
INSERT INTO banco(id, codigo, nome)VALUES(36,104,'CAIXA ECON. FEDERAL');
INSERT INTO banco(id, codigo, nome)VALUES(37,473,'CAIXA GERAL - BRASIL');
INSERT INTO banco(id, codigo, nome)VALUES(38,412,'CAPITAL');
INSERT INTO banco(id, codigo, nome)VALUES(39,040,'CARGILL');
INSERT INTO banco(id, codigo, nome)VALUES(40,114,'CC CECOOPES');
INSERT INTO banco(id, codigo, nome)VALUES(41,085,'CC CECRED');
INSERT INTO banco(id, codigo, nome)VALUES(42,097,'CC CENTRALCREDI');
INSERT INTO banco(id, codigo, nome)VALUES(43,098,'CC CREDIALIANÇA');
INSERT INTO banco(id, codigo, nome)VALUES(44,010,'CC CREDICOAMO');
INSERT INTO banco(id, codigo, nome)VALUES(45,089,'CC REGIÃO DA MOGIANA');
INSERT INTO banco(id, codigo, nome)VALUES(46,112,'CC UNICRED BRASIL CENTRAL');
INSERT INTO banco(id, codigo, nome)VALUES(47,091,'CC UNICRED CENTRAL RS');
INSERT INTO banco(id, codigo, nome)VALUES(48,087,'CC UNICRED CENTRAL SANTA CATARINA');
INSERT INTO banco(id, codigo, nome)VALUES(49,090,'CC UNICRED CENTRAL SP');
INSERT INTO banco(id, codigo, nome)VALUES(50,099,'CC UNIPRIME CENTRAL');
INSERT INTO banco(id, codigo, nome)VALUES(51,084,'CC UNIPRIME NORTE DO PARANÁ');
INSERT INTO banco(id, codigo, nome)VALUES(52,266,'CÉDULA');
INSERT INTO banco(id, codigo, nome)VALUES(53,083,'CHINA BRASIL');
INSERT INTO banco(id, codigo, nome)VALUES(54,233,'CIFRA');
INSERT INTO banco(id, codigo, nome)VALUES(55,477,'CITIBANK N. A.');
INSERT INTO banco(id, codigo, nome)VALUES(56,745,'CITIBANK S. A.');
INSERT INTO banco(id, codigo, nome)VALUES(57,241,'CLÁSSICO');
INSERT INTO banco(id, codigo, nome)VALUES(58,756,'COOPERATIVO BRASIL');
INSERT INTO banco(id, codigo, nome)VALUES(59,075,'CR2');
INSERT INTO banco(id, codigo, nome)VALUES(60,222,'CREDIT AGRÍCOLE BRASIL');
INSERT INTO banco(id, codigo, nome)VALUES(61,505,'CREDIT SUISSE');
INSERT INTO banco(id, codigo, nome)VALUES(62,707,'DAYCOVAL');
INSERT INTO banco(id, codigo, nome)VALUES(63,487,'DEUTSCHE BANK');
INSERT INTO banco(id, codigo, nome)VALUES(64,214,'DIBENS');
INSERT INTO banco(id, codigo, nome)VALUES(65,021,'EST. ES - BANESTES');
INSERT INTO banco(id, codigo, nome)VALUES(66,037,'EST. PA - BANPARÁ');
INSERT INTO banco(id, codigo, nome)VALUES(67,041,'EST. RS - BANRISUL');
INSERT INTO banco(id, codigo, nome)VALUES(68,047,'EST. SE - BANESE');
INSERT INTO banco(id, codigo, nome)VALUES(69,265,'FATOR');
INSERT INTO banco(id, codigo, nome)VALUES(70,224,'FIBRA');
INSERT INTO banco(id, codigo, nome)VALUES(71,626,'FICSA');
INSERT INTO banco(id, codigo, nome)VALUES(72,121,'GERADOR');
INSERT INTO banco(id, codigo, nome)VALUES(73,612,'GUANABARA');
INSERT INTO banco(id, codigo, nome)VALUES(74,062,'HIPERCARD');
INSERT INTO banco(id, codigo, nome)VALUES(75,399,'HSBC BANK');
INSERT INTO banco(id, codigo, nome)VALUES(76,604,'INDL. DO BRASIL');
INSERT INTO banco(id, codigo, nome)VALUES(77,320,'INDL. E COML.');
INSERT INTO banco(id, codigo, nome)VALUES(78,653,'INDUSVAL');
INSERT INTO banco(id, codigo, nome)VALUES(79,492,'ING BANK');
INSERT INTO banco(id, codigo, nome)VALUES(80,630,'INTERCAP');
INSERT INTO banco(id, codigo, nome)VALUES(81,077,'INTERMEDIUM');
INSERT INTO banco(id, codigo, nome)VALUES(82,249,'INVESTCRED');
INSERT INTO banco(id, codigo, nome)VALUES(83,184,'ITAÚ BBA');
INSERT INTO banco(id, codigo, nome)VALUES(84,341,'ITAÚ UNIBANCO');
INSERT INTO banco(id, codigo, nome)VALUES(85,652,'ITAÚ UNIBANCO HOLDING');
INSERT INTO banco(id, codigo, nome)VALUES(86,376,'J. P. MORGAN');
INSERT INTO banco(id, codigo, nome)VALUES(87,074,'J. SAFRA');
INSERT INTO banco(id, codigo, nome)VALUES(88,217,'JOHN DEERE');
INSERT INTO banco(id, codigo, nome)VALUES(89,488,'JP MORGAN CHASE BANK');
INSERT INTO banco(id, codigo, nome)VALUES(90,076,'KDB DO BRASIL');
INSERT INTO banco(id, codigo, nome)VALUES(91,757,'KEB DO BRASIL');
INSERT INTO banco(id, codigo, nome)VALUES(92,600,'LUSO BRASILEIRO');
INSERT INTO banco(id, codigo, nome)VALUES(93,243,'MÁXIMA');
INSERT INTO banco(id, codigo, nome)VALUES(94,389,'MERCANTIL DO BRASIL');
INSERT INTO banco(id, codigo, nome)VALUES(95,746,'MODAL');
INSERT INTO banco(id, codigo, nome)VALUES(96,066,'MORGAN STANLEY');
INSERT INTO banco(id, codigo, nome)VALUES(97,300,'NACION ARGENTINA');
INSERT INTO banco(id, codigo, nome)VALUES(98,753,'NBC BANK');
INSERT INTO banco(id, codigo, nome)VALUES(99,045,'OPPORTUNITY');
INSERT INTO banco(id, codigo, nome)VALUES(100,212,'ORIGINAL');
INSERT INTO banco(id, codigo, nome)VALUES(101,079,'ORIGINAL DO AGRONEGÓCIO');
INSERT INTO banco(id, codigo, nome)VALUES(102,623,'PANAMERICANO');
INSERT INTO banco(id, codigo, nome)VALUES(103,254,'PARANÁ');
INSERT INTO banco(id, codigo, nome)VALUES(104,611,'PAULISTA');
INSERT INTO banco(id, codigo, nome)VALUES(105,613,'PECÚNIA');
INSERT INTO banco(id, codigo, nome)VALUES(106,094,'PETRA');
INSERT INTO banco(id, codigo, nome)VALUES(107,643,'PINE');
INSERT INTO banco(id, codigo, nome)VALUES(108,735,'POTTENCIAL');
INSERT INTO banco(id, codigo, nome)VALUES(109,495,'PROVÍNCIA B. AIRES');
INSERT INTO banco(id, codigo, nome)VALUES(110,747,'RABOBANK');
INSERT INTO banco(id, codigo, nome)VALUES(111,088,'RANDON');
INSERT INTO banco(id, codigo, nome)VALUES(112,633,'RENDIMENTO');
INSERT INTO banco(id, codigo, nome)VALUES(113,494,'REP. OR. URUGUAY');
INSERT INTO banco(id, codigo, nome)VALUES(114,741,'RIBEIRÃO PRETO');
INSERT INTO banco(id, codigo, nome)VALUES(115,120,'RODOBENS');
INSERT INTO banco(id, codigo, nome)VALUES(116,453,'RURAL');
INSERT INTO banco(id, codigo, nome)VALUES(117,072,'RURAL MAIS');
INSERT INTO banco(id, codigo, nome)VALUES(118,422,'SAFRA');
INSERT INTO banco(id, codigo, nome)VALUES(119,033,'SANTANDER');
INSERT INTO banco(id, codigo, nome)VALUES(120,092,'SCFI BRICKELL');
INSERT INTO banco(id, codigo, nome)VALUES(121,751,'SCOTIABANK BRASIL');
INSERT INTO banco(id, codigo, nome)VALUES(122,743,'SEMEAR');
INSERT INTO banco(id, codigo, nome)VALUES(123,748,'SICREDI');
INSERT INTO banco(id, codigo, nome)VALUES(124,749,'SIMPLES');
INSERT INTO banco(id, codigo, nome)VALUES(125,366,'SOCIÉTÉ GÉNÉRALE');
INSERT INTO banco(id, codigo, nome)VALUES(126,637,'SOFISA');
INSERT INTO banco(id, codigo, nome)VALUES(127,464,'SUMITOMO MITSUI');
INSERT INTO banco(id, codigo, nome)VALUES(128,456,'TOKYO - MITSUBISHI UFJ');
INSERT INTO banco(id, codigo, nome)VALUES(129,082,'TOPAZIO');
INSERT INTO banco(id, codigo, nome)VALUES(130,634,'TRIÂNGULO');
INSERT INTO banco(id, codigo, nome)VALUES(131,409,'UNIBANCO');
INSERT INTO banco(id, codigo, nome)VALUES(132,655,'VOTORANTIM');
INSERT INTO banco(id, codigo, nome)VALUES(133,610,'VR');
INSERT INTO banco(id, codigo, nome)VALUES(134,119,'WESTERN UNION');
INSERT INTO banco(id, codigo, nome)VALUES(135,370,'WESTLB');
INSERT INTO banco(id, codigo, nome)VALUES(136,124,'WOORI BANK');
INSERT INTO banco(id, codigo, nome)VALUES(137,641,'ALVORADA');
INSERT INTO banco(id, codigo, nome)VALUES(138,024,'BANDEPE');
INSERT INTO banco(id, codigo, nome)VALUES(139,095,'BCAM CONFIDENCE');
INSERT INTO banco(id, codigo, nome)VALUES(140,126,'BI BR PARTNERS');
INSERT INTO banco(id, codigo, nome)VALUES(141,012,'BI STANDARD');
INSERT INTO banco(id, codigo, nome)VALUES(142,118,'BI STANDARD CHARTERED');
INSERT INTO banco(id, codigo, nome)VALUES(143,044,'BVA-SOB INTERVENÇÃO');
INSERT INTO banco(id, codigo, nome)VALUES(144,016,'CC CREDITRAN');
INSERT INTO banco(id, codigo, nome)VALUES(145,111,'DTVM OLIVEIRA TRUST');
INSERT INTO banco(id, codigo, nome)VALUES(146,101,'DTVM RENASCENÇA');
INSERT INTO banco(id, codigo, nome)VALUES(147,064,'GOLDMAN SACHS');
INSERT INTO banco(id, codigo, nome)VALUES(148,029,'ITAÚ CONSIGNADO');
INSERT INTO banco(id, codigo, nome)VALUES(149,479,'ITAUBANK');
INSERT INTO banco(id, codigo, nome)VALUES(150,014,'NATIXIS BRASIL');
INSERT INTO banco(id, codigo, nome)VALUES(151,117,'SC ADVANCED');
INSERT INTO banco(id, codigo, nome)VALUES(152,080,'SC BT ASSOCIADOS');
INSERT INTO banco(id, codigo, nome)VALUES(153,127,'SC CODEPE');
INSERT INTO banco(id, codigo, nome)VALUES(154,060,'SC CONFIDENCE');
INSERT INTO banco(id, codigo, nome)VALUES(155,011,'SC CREDIT SUISSE HG');
INSERT INTO banco(id, codigo, nome)VALUES(156,103,'SC EBS');
INSERT INTO banco(id, codigo, nome)VALUES(157,015,'SC LINK');
INSERT INTO banco(id, codigo, nome)VALUES(158,113,'SC MAGLIANO');
INSERT INTO banco(id, codigo, nome)VALUES(159,100,'SC PLANNER');
INSERT INTO banco(id, codigo, nome)VALUES(160,013,'SC SENSO');
INSERT INTO banco(id, codigo, nome)VALUES(161,901,'SC SOUZA BARROS');
INSERT INTO banco(id, codigo, nome)VALUES(162,102,'SC XP INVESTIMENTOS');
INSERT INTO banco(id, codigo, nome)VALUES(163,123,'SCFI AGIPLAN');
INSERT INTO banco(id, codigo, nome)VALUES(164,105,'SCFI LECCA');
INSERT INTO banco(id, codigo, nome)VALUES(165,108,'SCFI PORTOCRED');
INSERT INTO banco(id, codigo, nome)VALUES(166,093,'SCM PÓLOCRED');
INSERT INTO banco(id, codigo, nome)VALUES(167,230,'UNICARD');