// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Fashion.ERP.Web.Areas.Almoxarifado.Controllers
{
    public partial class MaterialController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected MaterialController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ObtenhaListaGridModel()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ObtenhaListaGridModel);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Editar()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Editar);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Excluir()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Excluir);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EditarSituacao()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditarSituacao);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LerReferenciaExternas()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LerReferenciaExternas);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AdicionarReferenciaExterna()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AdicionarReferenciaExterna);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult RemoverReferenciaExterna()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RemoverReferenciaExterna);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PesquisarFiltro()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PesquisarFiltro);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PesquisarReferencia()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PesquisarReferencia);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PesquisarId()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PesquisarId);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PesquisarFiltroReferenciaExterna()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PesquisarFiltroReferenciaExterna);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PesquisarReferenciaReferenciaExterna()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PesquisarReferenciaReferenciaExterna);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult PesquisarReferenciaExternaId()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PesquisarReferenciaExternaId);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult UnidadeMedida()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UnidadeMedida);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult QuantidadeEstoque()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.QuantidadeEstoque);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult VerificarReferencia()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.VerificarReferencia);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult ObtenhaCusto()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ObtenhaCusto);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult ObtenhaCustoAtual()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ObtenhaCustoAtual);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult ObtenhaGeneroCategoria()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ObtenhaGeneroCategoria);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public MaterialController Actions { get { return MVC.Almoxarifado.Material; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Almoxarifado";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Material";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Material";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string ObtenhaListaGridModel = "ObtenhaListaGridModel";
            public readonly string Novo = "Novo";
            public readonly string Editar = "Editar";
            public readonly string Excluir = "Excluir";
            public readonly string EditarSituacao = "EditarSituacao";
            public readonly string LerReferenciaExternas = "LerReferenciaExternas";
            public readonly string AdicionarReferenciaExterna = "AdicionarReferenciaExterna";
            public readonly string RemoverReferenciaExterna = "RemoverReferenciaExterna";
            public readonly string Pesquisar = "Pesquisar";
            public readonly string PesquisarVarios = "PesquisarVarios";
            public readonly string PesquisarFiltro = "PesquisarFiltro";
            public readonly string PesquisarReferencia = "PesquisarReferencia";
            public readonly string PesquisarId = "PesquisarId";
            public readonly string PesquisarReferenciaExterna = "PesquisarReferenciaExterna";
            public readonly string PesquisarFiltroReferenciaExterna = "PesquisarFiltroReferenciaExterna";
            public readonly string PesquisarReferenciaReferenciaExterna = "PesquisarReferenciaReferenciaExterna";
            public readonly string PesquisarReferenciaExternaId = "PesquisarReferenciaExternaId";
            public readonly string UnidadeMedida = "UnidadeMedida";
            public readonly string QuantidadeEstoque = "QuantidadeEstoque";
            public readonly string VerificarReferencia = "VerificarReferencia";
            public readonly string ObtenhaCusto = "ObtenhaCusto";
            public readonly string ObtenhaCustoAtual = "ObtenhaCustoAtual";
            public readonly string ObtenhaGeneroCategoria = "ObtenhaGeneroCategoria";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string ObtenhaListaGridModel = "ObtenhaListaGridModel";
            public const string Novo = "Novo";
            public const string Editar = "Editar";
            public const string Excluir = "Excluir";
            public const string EditarSituacao = "EditarSituacao";
            public const string LerReferenciaExternas = "LerReferenciaExternas";
            public const string AdicionarReferenciaExterna = "AdicionarReferenciaExterna";
            public const string RemoverReferenciaExterna = "RemoverReferenciaExterna";
            public const string Pesquisar = "Pesquisar";
            public const string PesquisarVarios = "PesquisarVarios";
            public const string PesquisarFiltro = "PesquisarFiltro";
            public const string PesquisarReferencia = "PesquisarReferencia";
            public const string PesquisarId = "PesquisarId";
            public const string PesquisarReferenciaExterna = "PesquisarReferenciaExterna";
            public const string PesquisarFiltroReferenciaExterna = "PesquisarFiltroReferenciaExterna";
            public const string PesquisarReferenciaReferenciaExterna = "PesquisarReferenciaReferenciaExterna";
            public const string PesquisarReferenciaExternaId = "PesquisarReferenciaExternaId";
            public const string UnidadeMedida = "UnidadeMedida";
            public const string QuantidadeEstoque = "QuantidadeEstoque";
            public const string VerificarReferencia = "VerificarReferencia";
            public const string ObtenhaCusto = "ObtenhaCusto";
            public const string ObtenhaCustoAtual = "ObtenhaCustoAtual";
            public const string ObtenhaGeneroCategoria = "ObtenhaGeneroCategoria";
        }


        static readonly ActionParamsClass_ObtenhaListaGridModel s_params_ObtenhaListaGridModel = new ActionParamsClass_ObtenhaListaGridModel();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ObtenhaListaGridModel ObtenhaListaGridModelParams { get { return s_params_ObtenhaListaGridModel; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ObtenhaListaGridModel
        {
            public readonly string request = "request";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Novo s_params_Novo = new ActionParamsClass_Novo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Novo NovoParams { get { return s_params_Novo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Novo
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Editar s_params_Editar = new ActionParamsClass_Editar();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Editar EditarParams { get { return s_params_Editar; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Editar
        {
            public readonly string id = "id";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Excluir s_params_Excluir = new ActionParamsClass_Excluir();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Excluir ExcluirParams { get { return s_params_Excluir; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Excluir
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_EditarSituacao s_params_EditarSituacao = new ActionParamsClass_EditarSituacao();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditarSituacao EditarSituacaoParams { get { return s_params_EditarSituacao; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditarSituacao
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_LerReferenciaExternas s_params_LerReferenciaExternas = new ActionParamsClass_LerReferenciaExternas();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LerReferenciaExternas LerReferenciaExternasParams { get { return s_params_LerReferenciaExternas; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LerReferenciaExternas
        {
            public readonly string request = "request";
        }
        static readonly ActionParamsClass_AdicionarReferenciaExterna s_params_AdicionarReferenciaExterna = new ActionParamsClass_AdicionarReferenciaExterna();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AdicionarReferenciaExterna AdicionarReferenciaExternaParams { get { return s_params_AdicionarReferenciaExterna; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AdicionarReferenciaExterna
        {
            public readonly string referenciaExterna = "referenciaExterna";
        }
        static readonly ActionParamsClass_RemoverReferenciaExterna s_params_RemoverReferenciaExterna = new ActionParamsClass_RemoverReferenciaExterna();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RemoverReferenciaExterna RemoverReferenciaExternaParams { get { return s_params_RemoverReferenciaExterna; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RemoverReferenciaExterna
        {
            public readonly string referenciaExterna = "referenciaExterna";
        }
        static readonly ActionParamsClass_PesquisarFiltro s_params_PesquisarFiltro = new ActionParamsClass_PesquisarFiltro();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PesquisarFiltro PesquisarFiltroParams { get { return s_params_PesquisarFiltro; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PesquisarFiltro
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_PesquisarReferencia s_params_PesquisarReferencia = new ActionParamsClass_PesquisarReferencia();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PesquisarReferencia PesquisarReferenciaParams { get { return s_params_PesquisarReferencia; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PesquisarReferencia
        {
            public readonly string referencia = "referencia";
            public readonly string tipoItemMaterial = "tipoItemMaterial";
            public readonly string fornecedorId = "fornecedorId";
        }
        static readonly ActionParamsClass_PesquisarId s_params_PesquisarId = new ActionParamsClass_PesquisarId();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PesquisarId PesquisarIdParams { get { return s_params_PesquisarId; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PesquisarId
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_PesquisarFiltroReferenciaExterna s_params_PesquisarFiltroReferenciaExterna = new ActionParamsClass_PesquisarFiltroReferenciaExterna();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PesquisarFiltroReferenciaExterna PesquisarFiltroReferenciaExternaParams { get { return s_params_PesquisarFiltroReferenciaExterna; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PesquisarFiltroReferenciaExterna
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_PesquisarReferenciaReferenciaExterna s_params_PesquisarReferenciaReferenciaExterna = new ActionParamsClass_PesquisarReferenciaReferenciaExterna();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PesquisarReferenciaReferenciaExterna PesquisarReferenciaReferenciaExternaParams { get { return s_params_PesquisarReferenciaReferenciaExterna; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PesquisarReferenciaReferenciaExterna
        {
            public readonly string referencia = "referencia";
        }
        static readonly ActionParamsClass_PesquisarReferenciaExternaId s_params_PesquisarReferenciaExternaId = new ActionParamsClass_PesquisarReferenciaExternaId();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_PesquisarReferenciaExternaId PesquisarReferenciaExternaIdParams { get { return s_params_PesquisarReferenciaExternaId; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_PesquisarReferenciaExternaId
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_UnidadeMedida s_params_UnidadeMedida = new ActionParamsClass_UnidadeMedida();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_UnidadeMedida UnidadeMedidaParams { get { return s_params_UnidadeMedida; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_UnidadeMedida
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_QuantidadeEstoque s_params_QuantidadeEstoque = new ActionParamsClass_QuantidadeEstoque();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_QuantidadeEstoque QuantidadeEstoqueParams { get { return s_params_QuantidadeEstoque; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_QuantidadeEstoque
        {
            public readonly string id = "id";
            public readonly string depositoId = "depositoId";
        }
        static readonly ActionParamsClass_VerificarReferencia s_params_VerificarReferencia = new ActionParamsClass_VerificarReferencia();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_VerificarReferencia VerificarReferenciaParams { get { return s_params_VerificarReferencia; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_VerificarReferencia
        {
            public readonly string referencia = "referencia";
        }
        static readonly ActionParamsClass_ObtenhaCusto s_params_ObtenhaCusto = new ActionParamsClass_ObtenhaCusto();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ObtenhaCusto ObtenhaCustoParams { get { return s_params_ObtenhaCusto; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ObtenhaCusto
        {
            public readonly string referencia = "referencia";
            public readonly string idFornecedor = "idFornecedor";
        }
        static readonly ActionParamsClass_ObtenhaCustoAtual s_params_ObtenhaCustoAtual = new ActionParamsClass_ObtenhaCustoAtual();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ObtenhaCustoAtual ObtenhaCustoAtualParams { get { return s_params_ObtenhaCustoAtual; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ObtenhaCustoAtual
        {
            public readonly string referencia = "referencia";
        }
        static readonly ActionParamsClass_ObtenhaGeneroCategoria s_params_ObtenhaGeneroCategoria = new ActionParamsClass_ObtenhaGeneroCategoria();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ObtenhaGeneroCategoria ObtenhaGeneroCategoriaParams { get { return s_params_ObtenhaGeneroCategoria; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ObtenhaGeneroCategoria
        {
            public readonly string referencia = "referencia";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _NovoOuEditar = "_NovoOuEditar";
                public readonly string Editar = "Editar";
                public readonly string Index = "Index";
                public readonly string Novo = "Novo";
                public readonly string Pesquisar = "Pesquisar";
                public readonly string PesquisarReferenciaExterna = "PesquisarReferenciaExterna";
                public readonly string PesquisarVarios = "PesquisarVarios";
            }
            public readonly string _NovoOuEditar = "~/Areas/Almoxarifado/Views/Material/_NovoOuEditar.cshtml";
            public readonly string Editar = "~/Areas/Almoxarifado/Views/Material/Editar.cshtml";
            public readonly string Index = "~/Areas/Almoxarifado/Views/Material/Index.cshtml";
            public readonly string Novo = "~/Areas/Almoxarifado/Views/Material/Novo.cshtml";
            public readonly string Pesquisar = "~/Areas/Almoxarifado/Views/Material/Pesquisar.cshtml";
            public readonly string PesquisarReferenciaExterna = "~/Areas/Almoxarifado/Views/Material/PesquisarReferenciaExterna.cshtml";
            public readonly string PesquisarVarios = "~/Areas/Almoxarifado/Views/Material/PesquisarVarios.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_MaterialController : Fashion.ERP.Web.Areas.Almoxarifado.Controllers.MaterialController
    {
        public T4MVC_MaterialController() : base(Dummy.Instance) { }

        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        partial void ObtenhaListaGridModelOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Kendo.Mvc.UI.DataSourceRequest request, Fashion.ERP.Web.Areas.Almoxarifado.Models.PesquisaMaterialModel model);

        public override System.Web.Mvc.ActionResult ObtenhaListaGridModel(Kendo.Mvc.UI.DataSourceRequest request, Fashion.ERP.Web.Areas.Almoxarifado.Models.PesquisaMaterialModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ObtenhaListaGridModel);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "request", request);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ObtenhaListaGridModelOverride(callInfo, request, model);
            return callInfo;
        }

        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Fashion.ERP.Web.Areas.Almoxarifado.Models.PesquisaMaterialModel model);

        public override System.Web.Mvc.ActionResult Index(Fashion.ERP.Web.Areas.Almoxarifado.Models.PesquisaMaterialModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            IndexOverride(callInfo, model);
            return callInfo;
        }

        partial void NovoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Novo()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Novo);
            NovoOverride(callInfo);
            return callInfo;
        }

        partial void NovoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Fashion.ERP.Web.Areas.Almoxarifado.Models.MaterialModel model);

        public override System.Web.Mvc.ActionResult Novo(Fashion.ERP.Web.Areas.Almoxarifado.Models.MaterialModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Novo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            NovoOverride(callInfo, model);
            return callInfo;
        }

        partial void EditarOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long id);

        public override System.Web.Mvc.ActionResult Editar(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Editar);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            EditarOverride(callInfo, id);
            return callInfo;
        }

        partial void EditarOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Fashion.ERP.Web.Areas.Almoxarifado.Models.MaterialModel model);

        public override System.Web.Mvc.ActionResult Editar(Fashion.ERP.Web.Areas.Almoxarifado.Models.MaterialModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Editar);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            EditarOverride(callInfo, model);
            return callInfo;
        }

        partial void ExcluirOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long? id);

        public override System.Web.Mvc.ActionResult Excluir(long? id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Excluir);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ExcluirOverride(callInfo, id);
            return callInfo;
        }

        partial void EditarSituacaoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long id);

        public override System.Web.Mvc.ActionResult EditarSituacao(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditarSituacao);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            EditarSituacaoOverride(callInfo, id);
            return callInfo;
        }

        partial void LerReferenciaExternasOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Kendo.Mvc.UI.DataSourceRequest request);

        public override System.Web.Mvc.ActionResult LerReferenciaExternas(Kendo.Mvc.UI.DataSourceRequest request)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LerReferenciaExternas);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "request", request);
            LerReferenciaExternasOverride(callInfo, request);
            return callInfo;
        }

        partial void AdicionarReferenciaExternaOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Fashion.ERP.Web.Areas.Almoxarifado.Models.ReferenciaExternaModel referenciaExterna);

        public override System.Web.Mvc.ActionResult AdicionarReferenciaExterna(Fashion.ERP.Web.Areas.Almoxarifado.Models.ReferenciaExternaModel referenciaExterna)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AdicionarReferenciaExterna);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "referenciaExterna", referenciaExterna);
            AdicionarReferenciaExternaOverride(callInfo, referenciaExterna);
            return callInfo;
        }

        partial void RemoverReferenciaExternaOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Fashion.ERP.Web.Areas.Almoxarifado.Models.ReferenciaExternaModel referenciaExterna);

        public override System.Web.Mvc.ActionResult RemoverReferenciaExterna(Fashion.ERP.Web.Areas.Almoxarifado.Models.ReferenciaExternaModel referenciaExterna)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RemoverReferenciaExterna);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "referenciaExterna", referenciaExterna);
            RemoverReferenciaExternaOverride(callInfo, referenciaExterna);
            return callInfo;
        }

        partial void PesquisarOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Pesquisar()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Pesquisar);
            PesquisarOverride(callInfo);
            return callInfo;
        }

        partial void PesquisarVariosOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult PesquisarVarios()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PesquisarVarios);
            PesquisarVariosOverride(callInfo);
            return callInfo;
        }

        partial void PesquisarFiltroOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Fashion.ERP.Web.Areas.Almoxarifado.Models.PesquisarMaterialModel model);

        public override System.Web.Mvc.ActionResult PesquisarFiltro(Fashion.ERP.Web.Areas.Almoxarifado.Models.PesquisarMaterialModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PesquisarFiltro);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            PesquisarFiltroOverride(callInfo, model);
            return callInfo;
        }

        partial void PesquisarReferenciaOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string referencia, long? tipoItemMaterial, long? fornecedorId);

        public override System.Web.Mvc.ActionResult PesquisarReferencia(string referencia, long? tipoItemMaterial, long? fornecedorId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PesquisarReferencia);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "referencia", referencia);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "tipoItemMaterial", tipoItemMaterial);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "fornecedorId", fornecedorId);
            PesquisarReferenciaOverride(callInfo, referencia, tipoItemMaterial, fornecedorId);
            return callInfo;
        }

        partial void PesquisarIdOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long id);

        public override System.Web.Mvc.ActionResult PesquisarId(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PesquisarId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            PesquisarIdOverride(callInfo, id);
            return callInfo;
        }

        partial void PesquisarReferenciaExternaOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult PesquisarReferenciaExterna()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PesquisarReferenciaExterna);
            PesquisarReferenciaExternaOverride(callInfo);
            return callInfo;
        }

        partial void PesquisarFiltroReferenciaExternaOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Fashion.ERP.Web.Models.PesquisarModel model);

        public override System.Web.Mvc.ActionResult PesquisarFiltroReferenciaExterna(Fashion.ERP.Web.Models.PesquisarModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PesquisarFiltroReferenciaExterna);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            PesquisarFiltroReferenciaExternaOverride(callInfo, model);
            return callInfo;
        }

        partial void PesquisarReferenciaReferenciaExternaOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string referencia);

        public override System.Web.Mvc.ActionResult PesquisarReferenciaReferenciaExterna(string referencia)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PesquisarReferenciaReferenciaExterna);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "referencia", referencia);
            PesquisarReferenciaReferenciaExternaOverride(callInfo, referencia);
            return callInfo;
        }

        partial void PesquisarReferenciaExternaIdOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long id);

        public override System.Web.Mvc.ActionResult PesquisarReferenciaExternaId(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.PesquisarReferenciaExternaId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            PesquisarReferenciaExternaIdOverride(callInfo, id);
            return callInfo;
        }

        partial void UnidadeMedidaOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long? id);

        public override System.Web.Mvc.ActionResult UnidadeMedida(long? id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.UnidadeMedida);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            UnidadeMedidaOverride(callInfo, id);
            return callInfo;
        }

        partial void QuantidadeEstoqueOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long? id, long? depositoId);

        public override System.Web.Mvc.ActionResult QuantidadeEstoque(long? id, long? depositoId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.QuantidadeEstoque);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "depositoId", depositoId);
            QuantidadeEstoqueOverride(callInfo, id, depositoId);
            return callInfo;
        }

        partial void VerificarReferenciaOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string referencia);

        public override System.Web.Mvc.JsonResult VerificarReferencia(string referencia)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.VerificarReferencia);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "referencia", referencia);
            VerificarReferenciaOverride(callInfo, referencia);
            return callInfo;
        }

        partial void ObtenhaCustoOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string referencia, long idFornecedor);

        public override System.Web.Mvc.JsonResult ObtenhaCusto(string referencia, long idFornecedor)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ObtenhaCusto);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "referencia", referencia);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "idFornecedor", idFornecedor);
            ObtenhaCustoOverride(callInfo, referencia, idFornecedor);
            return callInfo;
        }

        partial void ObtenhaCustoAtualOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string referencia);

        public override System.Web.Mvc.JsonResult ObtenhaCustoAtual(string referencia)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ObtenhaCustoAtual);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "referencia", referencia);
            ObtenhaCustoAtualOverride(callInfo, referencia);
            return callInfo;
        }

        partial void ObtenhaGeneroCategoriaOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string referencia);

        public override System.Web.Mvc.JsonResult ObtenhaGeneroCategoria(string referencia)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ObtenhaGeneroCategoria);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "referencia", referencia);
            ObtenhaGeneroCategoriaOverride(callInfo, referencia);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
