// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace T4MVC.Compras
{
    public class OrdemEntradaCompraController
    {

        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _NovoOuEditar = "_NovoOuEditar";
                public readonly string Detalhar = "Detalhar";
                public readonly string Editar = "Editar";
                public readonly string Index = "Index";
                public readonly string Novo = "Novo";
                public readonly string SelecionarPedidoCompra = "SelecionarPedidoCompra";
            }
            public readonly string _NovoOuEditar = "~/Areas/Compras/Views/OrdemEntradaCompra/_NovoOuEditar.cshtml";
            public readonly string Detalhar = "~/Areas/Compras/Views/OrdemEntradaCompra/Detalhar.cshtml";
            public readonly string Editar = "~/Areas/Compras/Views/OrdemEntradaCompra/Editar.cshtml";
            public readonly string Index = "~/Areas/Compras/Views/OrdemEntradaCompra/Index.cshtml";
            public readonly string Novo = "~/Areas/Compras/Views/OrdemEntradaCompra/Novo.cshtml";
            public readonly string SelecionarPedidoCompra = "~/Areas/Compras/Views/OrdemEntradaCompra/SelecionarPedidoCompra.cshtml";
        }
    }

}

#endregion T4MVC
#pragma warning restore 1591
