// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Fashion.ERP.Web.Areas.Compras.Controllers
{
    public partial class PedidoCompraCancelamentoController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected PedidoCompraCancelamentoController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult CancelamentoPedido()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CancelamentoPedido);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public PedidoCompraCancelamentoController Actions { get { return MVC.Compras.PedidoCompraCancelamento; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Compras";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "PedidoCompraCancelamento";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "PedidoCompraCancelamento";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string CancelamentoPedido = "CancelamentoPedido";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string CancelamentoPedido = "CancelamentoPedido";
        }


        static readonly ActionParamsClass_CancelamentoPedido s_params_CancelamentoPedido = new ActionParamsClass_CancelamentoPedido();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CancelamentoPedido CancelamentoPedidoParams { get { return s_params_CancelamentoPedido; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CancelamentoPedido
        {
            public readonly string id = "id";
            public readonly string model = "model";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string CancelamentoPedido = "CancelamentoPedido";
            }
            public readonly string CancelamentoPedido = "~/Areas/Compras/Views/PedidoCompraCancelamento/CancelamentoPedido.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_PedidoCompraCancelamentoController : Fashion.ERP.Web.Areas.Compras.Controllers.PedidoCompraCancelamentoController
    {
        public T4MVC_PedidoCompraCancelamentoController() : base(Dummy.Instance) { }

        partial void CancelamentoPedidoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long id);

        public override System.Web.Mvc.ActionResult CancelamentoPedido(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CancelamentoPedido);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            CancelamentoPedidoOverride(callInfo, id);
            return callInfo;
        }

        partial void CancelamentoPedidoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Fashion.ERP.Web.Areas.Compras.Models.PedidoCompraCancelamentoModel model);

        public override System.Web.Mvc.ActionResult CancelamentoPedido(Fashion.ERP.Web.Areas.Compras.Models.PedidoCompraCancelamentoModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.CancelamentoPedido);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            CancelamentoPedidoOverride(callInfo, model);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
