// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Fashion.ERP.Web.Areas.Comum.Controllers
{
    public partial class SetorProducaoController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected SetorProducaoController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Editar()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Editar);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Excluir()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Excluir);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EditarSituacao()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditarSituacao);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult SetoresDepartamento_()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SetoresDepartamento_);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult SetoresDepartamento()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SetoresDepartamento);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult SetoresDepartamento2()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SetoresDepartamento2);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult ObtenhaSetoresPorIdDepartamento()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ObtenhaSetoresPorIdDepartamento);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SetorProducaoController Actions { get { return MVC.Comum.SetorProducao; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Comum";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "SetorProducao";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "SetorProducao";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Novo = "Novo";
            public readonly string Editar = "Editar";
            public readonly string Excluir = "Excluir";
            public readonly string EditarSituacao = "EditarSituacao";
            public readonly string SetoresDepartamento_ = "SetoresDepartamento_";
            public readonly string SetoresDepartamento = "SetoresDepartamento";
            public readonly string SetoresDepartamento2 = "SetoresDepartamento2";
            public readonly string ObtenhaSetoresPorIdDepartamento = "ObtenhaSetoresPorIdDepartamento";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Novo = "Novo";
            public const string Editar = "Editar";
            public const string Excluir = "Excluir";
            public const string EditarSituacao = "EditarSituacao";
            public const string SetoresDepartamento_ = "SetoresDepartamento_";
            public const string SetoresDepartamento = "SetoresDepartamento";
            public const string SetoresDepartamento2 = "SetoresDepartamento2";
            public const string ObtenhaSetoresPorIdDepartamento = "ObtenhaSetoresPorIdDepartamento";
        }


        static readonly ActionParamsClass_Novo s_params_Novo = new ActionParamsClass_Novo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Novo NovoParams { get { return s_params_Novo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Novo
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Editar s_params_Editar = new ActionParamsClass_Editar();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Editar EditarParams { get { return s_params_Editar; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Editar
        {
            public readonly string id = "id";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Excluir s_params_Excluir = new ActionParamsClass_Excluir();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Excluir ExcluirParams { get { return s_params_Excluir; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Excluir
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_EditarSituacao s_params_EditarSituacao = new ActionParamsClass_EditarSituacao();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditarSituacao EditarSituacaoParams { get { return s_params_EditarSituacao; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditarSituacao
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_SetoresDepartamento_ s_params_SetoresDepartamento_ = new ActionParamsClass_SetoresDepartamento_();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SetoresDepartamento_ SetoresDepartamento_Params { get { return s_params_SetoresDepartamento_; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SetoresDepartamento_
        {
            public readonly string IdDepartamento = "IdDepartamento";
        }
        static readonly ActionParamsClass_SetoresDepartamento s_params_SetoresDepartamento = new ActionParamsClass_SetoresDepartamento();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SetoresDepartamento SetoresDepartamentoParams { get { return s_params_SetoresDepartamento; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SetoresDepartamento
        {
            public readonly string id = "id";
            public readonly string modeloId = "modeloId";
        }
        static readonly ActionParamsClass_SetoresDepartamento2 s_params_SetoresDepartamento2 = new ActionParamsClass_SetoresDepartamento2();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SetoresDepartamento2 SetoresDepartamento2Params { get { return s_params_SetoresDepartamento2; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SetoresDepartamento2
        {
            public readonly string NomeDepartamento = "NomeDepartamento";
        }
        static readonly ActionParamsClass_ObtenhaSetoresPorIdDepartamento s_params_ObtenhaSetoresPorIdDepartamento = new ActionParamsClass_ObtenhaSetoresPorIdDepartamento();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ObtenhaSetoresPorIdDepartamento ObtenhaSetoresPorIdDepartamentoParams { get { return s_params_ObtenhaSetoresPorIdDepartamento; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ObtenhaSetoresPorIdDepartamento
        {
            public readonly string DepartamentoProducao = "DepartamentoProducao";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _NovoOuEditar = "_NovoOuEditar";
                public readonly string Editar = "Editar";
                public readonly string Index = "Index";
                public readonly string Novo = "Novo";
            }
            public readonly string _NovoOuEditar = "~/Areas/Comum/Views/SetorProducao/_NovoOuEditar.cshtml";
            public readonly string Editar = "~/Areas/Comum/Views/SetorProducao/Editar.cshtml";
            public readonly string Index = "~/Areas/Comum/Views/SetorProducao/Index.cshtml";
            public readonly string Novo = "~/Areas/Comum/Views/SetorProducao/Novo.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_SetorProducaoController : Fashion.ERP.Web.Areas.Comum.Controllers.SetorProducaoController
    {
        public T4MVC_SetorProducaoController() : base(Dummy.Instance) { }

        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        partial void NovoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Novo()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Novo);
            NovoOverride(callInfo);
            return callInfo;
        }

        partial void NovoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Fashion.ERP.Web.Areas.Comum.Models.SetorProducaoModel model);

        public override System.Web.Mvc.ActionResult Novo(Fashion.ERP.Web.Areas.Comum.Models.SetorProducaoModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Novo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            NovoOverride(callInfo, model);
            return callInfo;
        }

        partial void EditarOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long id);

        public override System.Web.Mvc.ActionResult Editar(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Editar);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            EditarOverride(callInfo, id);
            return callInfo;
        }

        partial void EditarOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Fashion.ERP.Web.Areas.Comum.Models.SetorProducaoModel model);

        public override System.Web.Mvc.ActionResult Editar(Fashion.ERP.Web.Areas.Comum.Models.SetorProducaoModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Editar);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            EditarOverride(callInfo, model);
            return callInfo;
        }

        partial void ExcluirOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long? id);

        public override System.Web.Mvc.ActionResult Excluir(long? id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Excluir);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ExcluirOverride(callInfo, id);
            return callInfo;
        }

        partial void EditarSituacaoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long id);

        public override System.Web.Mvc.ActionResult EditarSituacao(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditarSituacao);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            EditarSituacaoOverride(callInfo, id);
            return callInfo;
        }

        partial void SetoresDepartamento_Override(T4MVC_System_Web_Mvc_JsonResult callInfo, long? IdDepartamento);

        public override System.Web.Mvc.JsonResult SetoresDepartamento_(long? IdDepartamento)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SetoresDepartamento_);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "IdDepartamento", IdDepartamento);
            SetoresDepartamento_Override(callInfo, IdDepartamento);
            return callInfo;
        }

        partial void SetoresDepartamentoOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, long? id, long? modeloId);

        public override System.Web.Mvc.JsonResult SetoresDepartamento(long? id, long? modeloId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SetoresDepartamento);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "modeloId", modeloId);
            SetoresDepartamentoOverride(callInfo, id, modeloId);
            return callInfo;
        }

        partial void SetoresDepartamento2Override(T4MVC_System_Web_Mvc_JsonResult callInfo, string NomeDepartamento);

        public override System.Web.Mvc.JsonResult SetoresDepartamento2(string NomeDepartamento)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SetoresDepartamento2);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "NomeDepartamento", NomeDepartamento);
            SetoresDepartamento2Override(callInfo, NomeDepartamento);
            return callInfo;
        }

        partial void ObtenhaSetoresPorIdDepartamentoOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string DepartamentoProducao);

        public override System.Web.Mvc.JsonResult ObtenhaSetoresPorIdDepartamento(string DepartamentoProducao)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.ObtenhaSetoresPorIdDepartamento);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "DepartamentoProducao", DepartamentoProducao);
            ObtenhaSetoresPorIdDepartamentoOverride(callInfo, DepartamentoProducao);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
