// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Fashion.ERP.Web.Areas.Comum.Controllers
{
    public partial class EnderecoController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected EnderecoController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Index()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LerEnderecos()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LerEnderecos);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult Cidades()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Cidades);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Novo()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Novo);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult Excluir()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Excluir);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public EnderecoController Actions { get { return MVC.Comum.Endereco; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Comum";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Endereco";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Endereco";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string LerEnderecos = "LerEnderecos";
            public readonly string Cidades = "Cidades";
            public readonly string Novo = "Novo";
            public readonly string Excluir = "Excluir";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string LerEnderecos = "LerEnderecos";
            public const string Cidades = "Cidades";
            public const string Novo = "Novo";
            public const string Excluir = "Excluir";
        }


        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string pessoaId = "pessoaId";
        }
        static readonly ActionParamsClass_LerEnderecos s_params_LerEnderecos = new ActionParamsClass_LerEnderecos();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LerEnderecos LerEnderecosParams { get { return s_params_LerEnderecos; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LerEnderecos
        {
            public readonly string request = "request";
            public readonly string pessoaId = "pessoaId";
        }
        static readonly ActionParamsClass_Cidades s_params_Cidades = new ActionParamsClass_Cidades();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Cidades CidadesParams { get { return s_params_Cidades; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Cidades
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Novo s_params_Novo = new ActionParamsClass_Novo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Novo NovoParams { get { return s_params_Novo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Novo
        {
            public readonly string pessoaId = "pessoaId";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Excluir s_params_Excluir = new ActionParamsClass_Excluir();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Excluir ExcluirParams { get { return s_params_Excluir; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Excluir
        {
            public readonly string request = "request";
            public readonly string model = "model";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string Index = "Index";
                public readonly string Novo = "Novo";
            }
            public readonly string Index = "~/Areas/Comum/Views/Endereco/Index.cshtml";
            public readonly string Novo = "~/Areas/Comum/Views/Endereco/Novo.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_EnderecoController : Fashion.ERP.Web.Areas.Comum.Controllers.EnderecoController
    {
        public T4MVC_EnderecoController() : base(Dummy.Instance) { }

        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long pessoaId);

        public override System.Web.Mvc.ActionResult Index(long pessoaId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "pessoaId", pessoaId);
            IndexOverride(callInfo, pessoaId);
            return callInfo;
        }

        partial void LerEnderecosOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Kendo.Mvc.UI.DataSourceRequest request, long pessoaId);

        public override System.Web.Mvc.ActionResult LerEnderecos(Kendo.Mvc.UI.DataSourceRequest request, long pessoaId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LerEnderecos);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "request", request);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "pessoaId", pessoaId);
            LerEnderecosOverride(callInfo, request, pessoaId);
            return callInfo;
        }

        partial void CidadesOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, long? id);

        public override System.Web.Mvc.JsonResult Cidades(long? id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Cidades);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            CidadesOverride(callInfo, id);
            return callInfo;
        }

        partial void NovoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long pessoaId);

        public override System.Web.Mvc.ActionResult Novo(long pessoaId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Novo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "pessoaId", pessoaId);
            NovoOverride(callInfo, pessoaId);
            return callInfo;
        }

        partial void NovoOverride(T4MVC_System_Web_Mvc_ContentResult callInfo, Fashion.ERP.Web.Areas.Comum.Models.EnderecoModel model);

        public override System.Web.Mvc.ContentResult Novo(Fashion.ERP.Web.Areas.Comum.Models.EnderecoModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ContentResult(Area, Name, ActionNames.Novo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            NovoOverride(callInfo, model);
            return callInfo;
        }

        partial void ExcluirOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, Kendo.Mvc.UI.DataSourceRequest request, Fashion.ERP.Web.Areas.Comum.Models.GridEnderecoModel model);

        public override System.Web.Mvc.JsonResult Excluir(Kendo.Mvc.UI.DataSourceRequest request, Fashion.ERP.Web.Areas.Comum.Models.GridEnderecoModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.Excluir);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "request", request);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ExcluirOverride(callInfo, request, model);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
