// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Fashion.ERP.Web.Areas.EngenhariaProduto.Controllers
{
    public partial class MaterialComposicaoModeloController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected MaterialComposicaoModeloController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult MaterialComposicaoModelo()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MaterialComposicaoModelo);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult CoresVariacao()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.CoresVariacao);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SequenciaProducao()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SequenciaProducao);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult SalveSequenciaProducao()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SalveSequenciaProducao);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AtualizeSequenciaProducao()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AtualizeSequenciaProducao);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ExcluaSequenciaProducao()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExcluaSequenciaProducao);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LerSequenciasProducao()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LerSequenciasProducao);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public MaterialComposicaoModeloController Actions { get { return MVC.EngenhariaProduto.MaterialComposicaoModelo; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "EngenhariaProduto";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "MaterialComposicaoModelo";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "MaterialComposicaoModelo";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string MaterialComposicaoModelo = "MaterialComposicaoModelo";
            public readonly string CoresVariacao = "CoresVariacao";
            public readonly string SequenciaProducao = "SequenciaProducao";
            public readonly string SalveSequenciaProducao = "SalveSequenciaProducao";
            public readonly string AtualizeSequenciaProducao = "AtualizeSequenciaProducao";
            public readonly string ExcluaSequenciaProducao = "ExcluaSequenciaProducao";
            public readonly string LerSequenciasProducao = "LerSequenciasProducao";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string MaterialComposicaoModelo = "MaterialComposicaoModelo";
            public const string CoresVariacao = "CoresVariacao";
            public const string SequenciaProducao = "SequenciaProducao";
            public const string SalveSequenciaProducao = "SalveSequenciaProducao";
            public const string AtualizeSequenciaProducao = "AtualizeSequenciaProducao";
            public const string ExcluaSequenciaProducao = "ExcluaSequenciaProducao";
            public const string LerSequenciasProducao = "LerSequenciasProducao";
        }


        static readonly ActionParamsClass_MaterialComposicaoModelo s_params_MaterialComposicaoModelo = new ActionParamsClass_MaterialComposicaoModelo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_MaterialComposicaoModelo MaterialComposicaoModeloParams { get { return s_params_MaterialComposicaoModelo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_MaterialComposicaoModelo
        {
            public readonly string modeloId = "modeloId";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_CoresVariacao s_params_CoresVariacao = new ActionParamsClass_CoresVariacao();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_CoresVariacao CoresVariacaoParams { get { return s_params_CoresVariacao; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_CoresVariacao
        {
            public readonly string variacaoModeloId = "variacaoModeloId";
        }
        static readonly ActionParamsClass_SequenciaProducao s_params_SequenciaProducao = new ActionParamsClass_SequenciaProducao();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SequenciaProducao SequenciaProducaoParams { get { return s_params_SequenciaProducao; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SequenciaProducao
        {
            public readonly string modeloId = "modeloId";
        }
        static readonly ActionParamsClass_SalveSequenciaProducao s_params_SalveSequenciaProducao = new ActionParamsClass_SalveSequenciaProducao();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SalveSequenciaProducao SalveSequenciaProducaoParams { get { return s_params_SalveSequenciaProducao; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SalveSequenciaProducao
        {
            public readonly string request = "request";
            public readonly string sequenciaProducoes = "models";
        }
        static readonly ActionParamsClass_AtualizeSequenciaProducao s_params_AtualizeSequenciaProducao = new ActionParamsClass_AtualizeSequenciaProducao();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AtualizeSequenciaProducao AtualizeSequenciaProducaoParams { get { return s_params_AtualizeSequenciaProducao; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AtualizeSequenciaProducao
        {
            public readonly string request = "request";
            public readonly string sequenciaProducoes = "models";
        }
        static readonly ActionParamsClass_ExcluaSequenciaProducao s_params_ExcluaSequenciaProducao = new ActionParamsClass_ExcluaSequenciaProducao();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ExcluaSequenciaProducao ExcluaSequenciaProducaoParams { get { return s_params_ExcluaSequenciaProducao; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ExcluaSequenciaProducao
        {
            public readonly string request = "request";
            public readonly string sequenciaProducoes = "models";
        }
        static readonly ActionParamsClass_LerSequenciasProducao s_params_LerSequenciasProducao = new ActionParamsClass_LerSequenciasProducao();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LerSequenciasProducao LerSequenciasProducaoParams { get { return s_params_LerSequenciasProducao; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LerSequenciasProducao
        {
            public readonly string request = "request";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string MaterialComposicaoModelo = "MaterialComposicaoModelo";
            }
            public readonly string MaterialComposicaoModelo = "~/Areas/EngenhariaProduto/Views/MaterialComposicaoModelo/MaterialComposicaoModelo.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_MaterialComposicaoModeloController : Fashion.ERP.Web.Areas.EngenhariaProduto.Controllers.MaterialComposicaoModeloController
    {
        public T4MVC_MaterialComposicaoModeloController() : base(Dummy.Instance) { }

        partial void MaterialComposicaoModeloOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long modeloId);

        public override System.Web.Mvc.ActionResult MaterialComposicaoModelo(long modeloId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MaterialComposicaoModelo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "modeloId", modeloId);
            MaterialComposicaoModeloOverride(callInfo, modeloId);
            return callInfo;
        }

        partial void MaterialComposicaoModeloOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Fashion.ERP.Web.Areas.EngenhariaProduto.Models.MaterialComposicaoModeloModel model);

        public override System.Web.Mvc.ActionResult MaterialComposicaoModelo(Fashion.ERP.Web.Areas.EngenhariaProduto.Models.MaterialComposicaoModeloModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MaterialComposicaoModelo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            MaterialComposicaoModeloOverride(callInfo, model);
            return callInfo;
        }

        partial void CoresVariacaoOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, long variacaoModeloId);

        public override System.Web.Mvc.JsonResult CoresVariacao(long variacaoModeloId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.CoresVariacao);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "variacaoModeloId", variacaoModeloId);
            CoresVariacaoOverride(callInfo, variacaoModeloId);
            return callInfo;
        }

        partial void SequenciaProducaoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long modeloId);

        public override System.Web.Mvc.ActionResult SequenciaProducao(long modeloId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SequenciaProducao);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "modeloId", modeloId);
            SequenciaProducaoOverride(callInfo, modeloId);
            return callInfo;
        }

        partial void SalveSequenciaProducaoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Kendo.Mvc.UI.DataSourceRequest request, System.Collections.Generic.IEnumerable<Fashion.ERP.Web.Areas.EngenhariaProduto.Models.SequenciaProducaoModel> sequenciaProducoes);

        public override System.Web.Mvc.ActionResult SalveSequenciaProducao(Kendo.Mvc.UI.DataSourceRequest request, System.Collections.Generic.IEnumerable<Fashion.ERP.Web.Areas.EngenhariaProduto.Models.SequenciaProducaoModel> sequenciaProducoes)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SalveSequenciaProducao);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "request", request);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "models", sequenciaProducoes);
            SalveSequenciaProducaoOverride(callInfo, request, sequenciaProducoes);
            return callInfo;
        }

        partial void AtualizeSequenciaProducaoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Kendo.Mvc.UI.DataSourceRequest request, System.Collections.Generic.IEnumerable<Fashion.ERP.Web.Areas.EngenhariaProduto.Models.SequenciaProducaoModel> sequenciaProducoes);

        public override System.Web.Mvc.ActionResult AtualizeSequenciaProducao(Kendo.Mvc.UI.DataSourceRequest request, System.Collections.Generic.IEnumerable<Fashion.ERP.Web.Areas.EngenhariaProduto.Models.SequenciaProducaoModel> sequenciaProducoes)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AtualizeSequenciaProducao);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "request", request);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "models", sequenciaProducoes);
            AtualizeSequenciaProducaoOverride(callInfo, request, sequenciaProducoes);
            return callInfo;
        }

        partial void ExcluaSequenciaProducaoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Kendo.Mvc.UI.DataSourceRequest request, System.Collections.Generic.IEnumerable<Fashion.ERP.Web.Areas.EngenhariaProduto.Models.SequenciaProducaoModel> sequenciaProducoes);

        public override System.Web.Mvc.ActionResult ExcluaSequenciaProducao(Kendo.Mvc.UI.DataSourceRequest request, System.Collections.Generic.IEnumerable<Fashion.ERP.Web.Areas.EngenhariaProduto.Models.SequenciaProducaoModel> sequenciaProducoes)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExcluaSequenciaProducao);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "request", request);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "models", sequenciaProducoes);
            ExcluaSequenciaProducaoOverride(callInfo, request, sequenciaProducoes);
            return callInfo;
        }

        partial void LerSequenciasProducaoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Kendo.Mvc.UI.DataSourceRequest request);

        public override System.Web.Mvc.ActionResult LerSequenciasProducao(Kendo.Mvc.UI.DataSourceRequest request)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LerSequenciasProducao);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "request", request);
            LerSequenciasProducaoOverride(callInfo, request);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
