// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Fashion.ERP.Web.Areas.EngenhariaProduto.Controllers
{
    public partial class RelatorioSolicitacaoMaterialCompraController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RelatorioSolicitacaoMaterialCompraController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public RelatorioSolicitacaoMaterialCompraController Actions { get { return MVC.EngenhariaProduto.RelatorioSolicitacaoMaterialCompra; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "EngenhariaProduto";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "RelatorioSolicitacaoMaterialCompra";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "RelatorioSolicitacaoMaterialCompra";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string SolicitacaoMaterialCompra = "SolicitacaoMaterialCompra";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string SolicitacaoMaterialCompra = "SolicitacaoMaterialCompra";
        }


        static readonly ActionParamsClass_SolicitacaoMaterialCompra s_params_SolicitacaoMaterialCompra = new ActionParamsClass_SolicitacaoMaterialCompra();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_SolicitacaoMaterialCompra SolicitacaoMaterialCompraParams { get { return s_params_SolicitacaoMaterialCompra; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_SolicitacaoMaterialCompra
        {
            public readonly string model = "model";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string SolicitacaoMaterialCompra = "SolicitacaoMaterialCompra";
            }
            public readonly string SolicitacaoMaterialCompra = "~/Areas/EngenhariaProduto/Views/RelatorioSolicitacaoMaterialCompra/SolicitacaoMaterialCompra.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_RelatorioSolicitacaoMaterialCompraController : Fashion.ERP.Web.Areas.EngenhariaProduto.Controllers.RelatorioSolicitacaoMaterialCompraController
    {
        public T4MVC_RelatorioSolicitacaoMaterialCompraController() : base(Dummy.Instance) { }

        partial void SolicitacaoMaterialCompraOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult SolicitacaoMaterialCompra()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.SolicitacaoMaterialCompra);
            SolicitacaoMaterialCompraOverride(callInfo);
            return callInfo;
        }

        partial void SolicitacaoMaterialCompraOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, Fashion.ERP.Web.Areas.EngenhariaProduto.Models.SolicitacaoMaterialCompraModel model);

        public override System.Web.Mvc.JsonResult SolicitacaoMaterialCompra(Fashion.ERP.Web.Areas.EngenhariaProduto.Models.SolicitacaoMaterialCompraModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.SolicitacaoMaterialCompra);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            SolicitacaoMaterialCompraOverride(callInfo, model);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
