// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Fashion.ERP.Web.Areas.EngenhariaProduto.Controllers
{
    public partial class ModeloController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ModeloController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Editar()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Editar);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Excluir()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Excluir);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Detalhar()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Detalhar);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Variacao()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Variacao);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Modelagem()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Modelagem);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ProgramacaoBordado()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ProgramacaoBordado);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult NovoProgramacaoBordado()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NovoProgramacaoBordado);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult EditarProgramacaoBordado()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditarProgramacaoBordado);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ExcluirProgramacaoBordado()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExcluirProgramacaoBordado);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LerFotos()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LerFotos);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AdicionarFoto()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AdicionarFoto);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult RemoverFoto()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RemoverFoto);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LerLinhaBordados()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LerLinhaBordados);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AdicionarLinhaBordado()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AdicionarLinhaBordado);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult RemoverLinhaBordado()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RemoverLinhaBordado);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LerLinhaPespontos()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LerLinhaPespontos);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AdicionarLinhaPesponto()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AdicionarLinhaPesponto);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult RemoverLinhaPesponto()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RemoverLinhaPesponto);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LerLinhaTravetes()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LerLinhaTravetes);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AdicionarLinhaTravete()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AdicionarLinhaTravete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult RemoverLinhaTravete()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RemoverLinhaTravete);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ImprimirDetalhe()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ImprimirDetalhe);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Copiar()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Copiar);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.JsonResult VerificarReferencia()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.VerificarReferencia);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ModeloController Actions { get { return MVC.EngenhariaProduto.Modelo; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "EngenhariaProduto";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Modelo";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Modelo";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Novo = "Novo";
            public readonly string Editar = "Editar";
            public readonly string Excluir = "Excluir";
            public readonly string Detalhar = "Detalhar";
            public readonly string Variacao = "Variacao";
            public readonly string Modelagem = "Modelagem";
            public readonly string ProgramacaoBordado = "ProgramacaoBordado";
            public readonly string NovoProgramacaoBordado = "NovoProgramacaoBordado";
            public readonly string EditarProgramacaoBordado = "EditarProgramacaoBordado";
            public readonly string ExcluirProgramacaoBordado = "ExcluirProgramacaoBordado";
            public readonly string LerFotos = "LerFotos";
            public readonly string AdicionarFoto = "AdicionarFoto";
            public readonly string RemoverFoto = "RemoverFoto";
            public readonly string LerLinhaBordados = "LerLinhaBordados";
            public readonly string AdicionarLinhaBordado = "AdicionarLinhaBordado";
            public readonly string RemoverLinhaBordado = "RemoverLinhaBordado";
            public readonly string LerLinhaPespontos = "LerLinhaPespontos";
            public readonly string AdicionarLinhaPesponto = "AdicionarLinhaPesponto";
            public readonly string RemoverLinhaPesponto = "RemoverLinhaPesponto";
            public readonly string LerLinhaTravetes = "LerLinhaTravetes";
            public readonly string AdicionarLinhaTravete = "AdicionarLinhaTravete";
            public readonly string RemoverLinhaTravete = "RemoverLinhaTravete";
            public readonly string ImprimirDetalhe = "ImprimirDetalhe";
            public readonly string Copiar = "Copiar";
            public readonly string VerificarReferencia = "VerificarReferencia";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Novo = "Novo";
            public const string Editar = "Editar";
            public const string Excluir = "Excluir";
            public const string Detalhar = "Detalhar";
            public const string Variacao = "Variacao";
            public const string Modelagem = "Modelagem";
            public const string ProgramacaoBordado = "ProgramacaoBordado";
            public const string NovoProgramacaoBordado = "NovoProgramacaoBordado";
            public const string EditarProgramacaoBordado = "EditarProgramacaoBordado";
            public const string ExcluirProgramacaoBordado = "ExcluirProgramacaoBordado";
            public const string LerFotos = "LerFotos";
            public const string AdicionarFoto = "AdicionarFoto";
            public const string RemoverFoto = "RemoverFoto";
            public const string LerLinhaBordados = "LerLinhaBordados";
            public const string AdicionarLinhaBordado = "AdicionarLinhaBordado";
            public const string RemoverLinhaBordado = "RemoverLinhaBordado";
            public const string LerLinhaPespontos = "LerLinhaPespontos";
            public const string AdicionarLinhaPesponto = "AdicionarLinhaPesponto";
            public const string RemoverLinhaPesponto = "RemoverLinhaPesponto";
            public const string LerLinhaTravetes = "LerLinhaTravetes";
            public const string AdicionarLinhaTravete = "AdicionarLinhaTravete";
            public const string RemoverLinhaTravete = "RemoverLinhaTravete";
            public const string ImprimirDetalhe = "ImprimirDetalhe";
            public const string Copiar = "Copiar";
            public const string VerificarReferencia = "VerificarReferencia";
        }


        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Novo s_params_Novo = new ActionParamsClass_Novo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Novo NovoParams { get { return s_params_Novo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Novo
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Editar s_params_Editar = new ActionParamsClass_Editar();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Editar EditarParams { get { return s_params_Editar; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Editar
        {
            public readonly string modeloId = "modeloId";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Excluir s_params_Excluir = new ActionParamsClass_Excluir();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Excluir ExcluirParams { get { return s_params_Excluir; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Excluir
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Detalhar s_params_Detalhar = new ActionParamsClass_Detalhar();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Detalhar DetalharParams { get { return s_params_Detalhar; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Detalhar
        {
            public readonly string modeloId = "modeloId";
        }
        static readonly ActionParamsClass_Variacao s_params_Variacao = new ActionParamsClass_Variacao();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Variacao VariacaoParams { get { return s_params_Variacao; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Variacao
        {
            public readonly string modeloId = "modeloId";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Modelagem s_params_Modelagem = new ActionParamsClass_Modelagem();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Modelagem ModelagemParams { get { return s_params_Modelagem; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Modelagem
        {
            public readonly string modeloId = "modeloId";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_ProgramacaoBordado s_params_ProgramacaoBordado = new ActionParamsClass_ProgramacaoBordado();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ProgramacaoBordado ProgramacaoBordadoParams { get { return s_params_ProgramacaoBordado; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ProgramacaoBordado
        {
            public readonly string modeloId = "modeloId";
        }
        static readonly ActionParamsClass_NovoProgramacaoBordado s_params_NovoProgramacaoBordado = new ActionParamsClass_NovoProgramacaoBordado();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_NovoProgramacaoBordado NovoProgramacaoBordadoParams { get { return s_params_NovoProgramacaoBordado; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_NovoProgramacaoBordado
        {
            public readonly string modeloId = "modeloId";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_EditarProgramacaoBordado s_params_EditarProgramacaoBordado = new ActionParamsClass_EditarProgramacaoBordado();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditarProgramacaoBordado EditarProgramacaoBordadoParams { get { return s_params_EditarProgramacaoBordado; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditarProgramacaoBordado
        {
            public readonly string modeloId = "modeloId";
            public readonly string id = "id";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_ExcluirProgramacaoBordado s_params_ExcluirProgramacaoBordado = new ActionParamsClass_ExcluirProgramacaoBordado();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ExcluirProgramacaoBordado ExcluirProgramacaoBordadoParams { get { return s_params_ExcluirProgramacaoBordado; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ExcluirProgramacaoBordado
        {
            public readonly string modeloId = "modeloId";
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_LerFotos s_params_LerFotos = new ActionParamsClass_LerFotos();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LerFotos LerFotosParams { get { return s_params_LerFotos; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LerFotos
        {
            public readonly string request = "request";
        }
        static readonly ActionParamsClass_AdicionarFoto s_params_AdicionarFoto = new ActionParamsClass_AdicionarFoto();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AdicionarFoto AdicionarFotoParams { get { return s_params_AdicionarFoto; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AdicionarFoto
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_RemoverFoto s_params_RemoverFoto = new ActionParamsClass_RemoverFoto();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RemoverFoto RemoverFotoParams { get { return s_params_RemoverFoto; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RemoverFoto
        {
            public readonly string fotoNome = "fotoNome";
        }
        static readonly ActionParamsClass_LerLinhaBordados s_params_LerLinhaBordados = new ActionParamsClass_LerLinhaBordados();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LerLinhaBordados LerLinhaBordadosParams { get { return s_params_LerLinhaBordados; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LerLinhaBordados
        {
            public readonly string request = "request";
        }
        static readonly ActionParamsClass_AdicionarLinhaBordado s_params_AdicionarLinhaBordado = new ActionParamsClass_AdicionarLinhaBordado();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AdicionarLinhaBordado AdicionarLinhaBordadoParams { get { return s_params_AdicionarLinhaBordado; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AdicionarLinhaBordado
        {
            public readonly string nome = "nome";
        }
        static readonly ActionParamsClass_RemoverLinhaBordado s_params_RemoverLinhaBordado = new ActionParamsClass_RemoverLinhaBordado();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RemoverLinhaBordado RemoverLinhaBordadoParams { get { return s_params_RemoverLinhaBordado; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RemoverLinhaBordado
        {
            public readonly string nome = "nome";
        }
        static readonly ActionParamsClass_LerLinhaPespontos s_params_LerLinhaPespontos = new ActionParamsClass_LerLinhaPespontos();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LerLinhaPespontos LerLinhaPespontosParams { get { return s_params_LerLinhaPespontos; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LerLinhaPespontos
        {
            public readonly string request = "request";
        }
        static readonly ActionParamsClass_AdicionarLinhaPesponto s_params_AdicionarLinhaPesponto = new ActionParamsClass_AdicionarLinhaPesponto();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AdicionarLinhaPesponto AdicionarLinhaPespontoParams { get { return s_params_AdicionarLinhaPesponto; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AdicionarLinhaPesponto
        {
            public readonly string nome = "nome";
        }
        static readonly ActionParamsClass_RemoverLinhaPesponto s_params_RemoverLinhaPesponto = new ActionParamsClass_RemoverLinhaPesponto();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RemoverLinhaPesponto RemoverLinhaPespontoParams { get { return s_params_RemoverLinhaPesponto; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RemoverLinhaPesponto
        {
            public readonly string nome = "nome";
        }
        static readonly ActionParamsClass_LerLinhaTravetes s_params_LerLinhaTravetes = new ActionParamsClass_LerLinhaTravetes();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LerLinhaTravetes LerLinhaTravetesParams { get { return s_params_LerLinhaTravetes; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LerLinhaTravetes
        {
            public readonly string request = "request";
        }
        static readonly ActionParamsClass_AdicionarLinhaTravete s_params_AdicionarLinhaTravete = new ActionParamsClass_AdicionarLinhaTravete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AdicionarLinhaTravete AdicionarLinhaTraveteParams { get { return s_params_AdicionarLinhaTravete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AdicionarLinhaTravete
        {
            public readonly string nome = "nome";
        }
        static readonly ActionParamsClass_RemoverLinhaTravete s_params_RemoverLinhaTravete = new ActionParamsClass_RemoverLinhaTravete();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RemoverLinhaTravete RemoverLinhaTraveteParams { get { return s_params_RemoverLinhaTravete; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RemoverLinhaTravete
        {
            public readonly string nome = "nome";
        }
        static readonly ActionParamsClass_ImprimirDetalhe s_params_ImprimirDetalhe = new ActionParamsClass_ImprimirDetalhe();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ImprimirDetalhe ImprimirDetalheParams { get { return s_params_ImprimirDetalhe; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ImprimirDetalhe
        {
            public readonly string modeloId = "modeloId";
        }
        static readonly ActionParamsClass_Copiar s_params_Copiar = new ActionParamsClass_Copiar();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Copiar CopiarParams { get { return s_params_Copiar; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Copiar
        {
            public readonly string modeloId = "modeloId";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_VerificarReferencia s_params_VerificarReferencia = new ActionParamsClass_VerificarReferencia();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_VerificarReferencia VerificarReferenciaParams { get { return s_params_VerificarReferencia; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_VerificarReferencia
        {
            public readonly string referencia = "referencia";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _NovoOuEditar = "_NovoOuEditar";
                public readonly string _NovoOuEditarProgramacaoBordado = "_NovoOuEditarProgramacaoBordado";
                public readonly string Copiar = "Copiar";
                public readonly string Detalhar = "Detalhar";
                public readonly string Editar = "Editar";
                public readonly string EditarProgramacaoBordado = "EditarProgramacaoBordado";
                public readonly string Index = "Index";
                public readonly string Modelagem = "Modelagem";
                public readonly string Novo = "Novo";
                public readonly string NovoProgramacaoBordado = "NovoProgramacaoBordado";
                public readonly string ProgramacaoBordado = "ProgramacaoBordado";
                public readonly string Variacao = "Variacao";
            }
            public readonly string _NovoOuEditar = "~/Areas/EngenhariaProduto/Views/Modelo/_NovoOuEditar.cshtml";
            public readonly string _NovoOuEditarProgramacaoBordado = "~/Areas/EngenhariaProduto/Views/Modelo/_NovoOuEditarProgramacaoBordado.cshtml";
            public readonly string Copiar = "~/Areas/EngenhariaProduto/Views/Modelo/Copiar.cshtml";
            public readonly string Detalhar = "~/Areas/EngenhariaProduto/Views/Modelo/Detalhar.cshtml";
            public readonly string Editar = "~/Areas/EngenhariaProduto/Views/Modelo/Editar.cshtml";
            public readonly string EditarProgramacaoBordado = "~/Areas/EngenhariaProduto/Views/Modelo/EditarProgramacaoBordado.cshtml";
            public readonly string Index = "~/Areas/EngenhariaProduto/Views/Modelo/Index.cshtml";
            public readonly string Modelagem = "~/Areas/EngenhariaProduto/Views/Modelo/Modelagem.cshtml";
            public readonly string Novo = "~/Areas/EngenhariaProduto/Views/Modelo/Novo.cshtml";
            public readonly string NovoProgramacaoBordado = "~/Areas/EngenhariaProduto/Views/Modelo/NovoProgramacaoBordado.cshtml";
            public readonly string ProgramacaoBordado = "~/Areas/EngenhariaProduto/Views/Modelo/ProgramacaoBordado.cshtml";
            public readonly string Variacao = "~/Areas/EngenhariaProduto/Views/Modelo/Variacao.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ModeloController : Fashion.ERP.Web.Areas.EngenhariaProduto.Controllers.ModeloController
    {
        public T4MVC_ModeloController() : base(Dummy.Instance) { }

        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Fashion.ERP.Web.Areas.EngenhariaProduto.Models.PesquisaModeloModel model);

        public override System.Web.Mvc.ActionResult Index(Fashion.ERP.Web.Areas.EngenhariaProduto.Models.PesquisaModeloModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            IndexOverride(callInfo, model);
            return callInfo;
        }

        partial void NovoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Novo()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Novo);
            NovoOverride(callInfo);
            return callInfo;
        }

        partial void NovoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Fashion.ERP.Web.Areas.EngenhariaProduto.Models.ModeloModel model);

        public override System.Web.Mvc.ActionResult Novo(Fashion.ERP.Web.Areas.EngenhariaProduto.Models.ModeloModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Novo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            NovoOverride(callInfo, model);
            return callInfo;
        }

        partial void EditarOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long modeloId);

        public override System.Web.Mvc.ActionResult Editar(long modeloId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Editar);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "modeloId", modeloId);
            EditarOverride(callInfo, modeloId);
            return callInfo;
        }

        partial void EditarOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Fashion.ERP.Web.Areas.EngenhariaProduto.Models.ModeloModel model);

        public override System.Web.Mvc.ActionResult Editar(Fashion.ERP.Web.Areas.EngenhariaProduto.Models.ModeloModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Editar);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            EditarOverride(callInfo, model);
            return callInfo;
        }

        partial void ExcluirOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long? id);

        public override System.Web.Mvc.ActionResult Excluir(long? id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Excluir);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ExcluirOverride(callInfo, id);
            return callInfo;
        }

        partial void DetalharOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long modeloId);

        public override System.Web.Mvc.ActionResult Detalhar(long modeloId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Detalhar);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "modeloId", modeloId);
            DetalharOverride(callInfo, modeloId);
            return callInfo;
        }

        partial void VariacaoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long modeloId);

        public override System.Web.Mvc.ActionResult Variacao(long modeloId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Variacao);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "modeloId", modeloId);
            VariacaoOverride(callInfo, modeloId);
            return callInfo;
        }

        partial void VariacaoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Fashion.ERP.Web.Areas.EngenhariaProduto.Models.VariacaoModeloModel model);

        public override System.Web.Mvc.ActionResult Variacao(Fashion.ERP.Web.Areas.EngenhariaProduto.Models.VariacaoModeloModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Variacao);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            VariacaoOverride(callInfo, model);
            return callInfo;
        }

        partial void ModelagemOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long modeloId);

        public override System.Web.Mvc.ActionResult Modelagem(long modeloId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Modelagem);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "modeloId", modeloId);
            ModelagemOverride(callInfo, modeloId);
            return callInfo;
        }

        partial void ModelagemOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Fashion.ERP.Web.Areas.EngenhariaProduto.Models.ModelagemModeloModel model);

        public override System.Web.Mvc.ActionResult Modelagem(Fashion.ERP.Web.Areas.EngenhariaProduto.Models.ModelagemModeloModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Modelagem);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelagemOverride(callInfo, model);
            return callInfo;
        }

        partial void ProgramacaoBordadoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long modeloId);

        public override System.Web.Mvc.ActionResult ProgramacaoBordado(long modeloId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ProgramacaoBordado);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "modeloId", modeloId);
            ProgramacaoBordadoOverride(callInfo, modeloId);
            return callInfo;
        }

        partial void NovoProgramacaoBordadoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long modeloId);

        public override System.Web.Mvc.ActionResult NovoProgramacaoBordado(long modeloId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NovoProgramacaoBordado);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "modeloId", modeloId);
            NovoProgramacaoBordadoOverride(callInfo, modeloId);
            return callInfo;
        }

        partial void NovoProgramacaoBordadoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long modeloId, Fashion.ERP.Web.Areas.EngenhariaProduto.Models.ProgramacaoBordadoModel model);

        public override System.Web.Mvc.ActionResult NovoProgramacaoBordado(long modeloId, Fashion.ERP.Web.Areas.EngenhariaProduto.Models.ProgramacaoBordadoModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NovoProgramacaoBordado);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "modeloId", modeloId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            NovoProgramacaoBordadoOverride(callInfo, modeloId, model);
            return callInfo;
        }

        partial void EditarProgramacaoBordadoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long modeloId, long id);

        public override System.Web.Mvc.ActionResult EditarProgramacaoBordado(long modeloId, long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditarProgramacaoBordado);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "modeloId", modeloId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            EditarProgramacaoBordadoOverride(callInfo, modeloId, id);
            return callInfo;
        }

        partial void EditarProgramacaoBordadoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long modeloId, Fashion.ERP.Web.Areas.EngenhariaProduto.Models.ProgramacaoBordadoModel model);

        public override System.Web.Mvc.ActionResult EditarProgramacaoBordado(long modeloId, Fashion.ERP.Web.Areas.EngenhariaProduto.Models.ProgramacaoBordadoModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditarProgramacaoBordado);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "modeloId", modeloId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            EditarProgramacaoBordadoOverride(callInfo, modeloId, model);
            return callInfo;
        }

        partial void ExcluirProgramacaoBordadoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long? modeloId, long? id);

        public override System.Web.Mvc.ActionResult ExcluirProgramacaoBordado(long? modeloId, long? id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExcluirProgramacaoBordado);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "modeloId", modeloId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ExcluirProgramacaoBordadoOverride(callInfo, modeloId, id);
            return callInfo;
        }

        partial void LerFotosOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Kendo.Mvc.UI.DataSourceRequest request);

        public override System.Web.Mvc.ActionResult LerFotos(Kendo.Mvc.UI.DataSourceRequest request)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LerFotos);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "request", request);
            LerFotosOverride(callInfo, request);
            return callInfo;
        }

        partial void AdicionarFotoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Fashion.ERP.Web.Areas.EngenhariaProduto.Models.ModeloFotoModel model);

        public override System.Web.Mvc.ActionResult AdicionarFoto(Fashion.ERP.Web.Areas.EngenhariaProduto.Models.ModeloFotoModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AdicionarFoto);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            AdicionarFotoOverride(callInfo, model);
            return callInfo;
        }

        partial void RemoverFotoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string fotoNome);

        public override System.Web.Mvc.ActionResult RemoverFoto(string fotoNome)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RemoverFoto);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "fotoNome", fotoNome);
            RemoverFotoOverride(callInfo, fotoNome);
            return callInfo;
        }

        partial void LerLinhaBordadosOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Kendo.Mvc.UI.DataSourceRequest request);

        public override System.Web.Mvc.ActionResult LerLinhaBordados(Kendo.Mvc.UI.DataSourceRequest request)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LerLinhaBordados);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "request", request);
            LerLinhaBordadosOverride(callInfo, request);
            return callInfo;
        }

        partial void AdicionarLinhaBordadoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string nome);

        public override System.Web.Mvc.ActionResult AdicionarLinhaBordado(string nome)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AdicionarLinhaBordado);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "nome", nome);
            AdicionarLinhaBordadoOverride(callInfo, nome);
            return callInfo;
        }

        partial void RemoverLinhaBordadoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string nome);

        public override System.Web.Mvc.ActionResult RemoverLinhaBordado(string nome)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RemoverLinhaBordado);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "nome", nome);
            RemoverLinhaBordadoOverride(callInfo, nome);
            return callInfo;
        }

        partial void LerLinhaPespontosOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Kendo.Mvc.UI.DataSourceRequest request);

        public override System.Web.Mvc.ActionResult LerLinhaPespontos(Kendo.Mvc.UI.DataSourceRequest request)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LerLinhaPespontos);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "request", request);
            LerLinhaPespontosOverride(callInfo, request);
            return callInfo;
        }

        partial void AdicionarLinhaPespontoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string nome);

        public override System.Web.Mvc.ActionResult AdicionarLinhaPesponto(string nome)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AdicionarLinhaPesponto);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "nome", nome);
            AdicionarLinhaPespontoOverride(callInfo, nome);
            return callInfo;
        }

        partial void RemoverLinhaPespontoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string nome);

        public override System.Web.Mvc.ActionResult RemoverLinhaPesponto(string nome)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RemoverLinhaPesponto);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "nome", nome);
            RemoverLinhaPespontoOverride(callInfo, nome);
            return callInfo;
        }

        partial void LerLinhaTravetesOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Kendo.Mvc.UI.DataSourceRequest request);

        public override System.Web.Mvc.ActionResult LerLinhaTravetes(Kendo.Mvc.UI.DataSourceRequest request)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LerLinhaTravetes);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "request", request);
            LerLinhaTravetesOverride(callInfo, request);
            return callInfo;
        }

        partial void AdicionarLinhaTraveteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string nome);

        public override System.Web.Mvc.ActionResult AdicionarLinhaTravete(string nome)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AdicionarLinhaTravete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "nome", nome);
            AdicionarLinhaTraveteOverride(callInfo, nome);
            return callInfo;
        }

        partial void RemoverLinhaTraveteOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, string nome);

        public override System.Web.Mvc.ActionResult RemoverLinhaTravete(string nome)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RemoverLinhaTravete);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "nome", nome);
            RemoverLinhaTraveteOverride(callInfo, nome);
            return callInfo;
        }

        partial void ImprimirDetalheOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long modeloId);

        public override System.Web.Mvc.ActionResult ImprimirDetalhe(long modeloId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ImprimirDetalhe);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "modeloId", modeloId);
            ImprimirDetalheOverride(callInfo, modeloId);
            return callInfo;
        }

        partial void CopiarOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long modeloId);

        public override System.Web.Mvc.ActionResult Copiar(long modeloId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Copiar);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "modeloId", modeloId);
            CopiarOverride(callInfo, modeloId);
            return callInfo;
        }

        partial void CopiarOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Fashion.ERP.Web.Areas.EngenhariaProduto.Models.CopidarModeloModel model);

        public override System.Web.Mvc.ActionResult Copiar(Fashion.ERP.Web.Areas.EngenhariaProduto.Models.CopidarModeloModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Copiar);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            CopiarOverride(callInfo, model);
            return callInfo;
        }

        partial void VerificarReferenciaOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, string referencia);

        public override System.Web.Mvc.JsonResult VerificarReferencia(string referencia)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.VerificarReferencia);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "referencia", referencia);
            VerificarReferenciaOverride(callInfo, referencia);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
