// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Fashion.ERP.Web.Areas.Financeiro.Controllers
{
    public partial class ChequeRecebidoController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ChequeRecebidoController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Editar()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Editar);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Excluir()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Excluir);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Baixa()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Baixa);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Devolucao()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Devolucao);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult ExcluirBaixa()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExcluirBaixa);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LerFuncionarios()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LerFuncionarios);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AdicionarFuncionario()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AdicionarFuncionario);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult RemoverFuncionario()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RemoverFuncionario);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LerPrestadores()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LerPrestadores);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult AdicionarPrestador()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AdicionarPrestador);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult RemoverPrestador()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RemoverPrestador);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LerOcorrencias()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LerOcorrencias);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult LerBaixasRealizadas()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LerBaixasRealizadas);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ChequeRecebidoController Actions { get { return MVC.Financeiro.ChequeRecebido; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Financeiro";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "ChequeRecebido";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "ChequeRecebido";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Index = "Index";
            public readonly string Novo = "Novo";
            public readonly string Editar = "Editar";
            public readonly string Excluir = "Excluir";
            public readonly string Baixa = "Baixa";
            public readonly string Devolucao = "Devolucao";
            public readonly string ExcluirBaixa = "ExcluirBaixa";
            public readonly string LerFuncionarios = "LerFuncionarios";
            public readonly string AdicionarFuncionario = "AdicionarFuncionario";
            public readonly string RemoverFuncionario = "RemoverFuncionario";
            public readonly string LerPrestadores = "LerPrestadores";
            public readonly string AdicionarPrestador = "AdicionarPrestador";
            public readonly string RemoverPrestador = "RemoverPrestador";
            public readonly string LerOcorrencias = "LerOcorrencias";
            public readonly string LerBaixasRealizadas = "LerBaixasRealizadas";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Index = "Index";
            public const string Novo = "Novo";
            public const string Editar = "Editar";
            public const string Excluir = "Excluir";
            public const string Baixa = "Baixa";
            public const string Devolucao = "Devolucao";
            public const string ExcluirBaixa = "ExcluirBaixa";
            public const string LerFuncionarios = "LerFuncionarios";
            public const string AdicionarFuncionario = "AdicionarFuncionario";
            public const string RemoverFuncionario = "RemoverFuncionario";
            public const string LerPrestadores = "LerPrestadores";
            public const string AdicionarPrestador = "AdicionarPrestador";
            public const string RemoverPrestador = "RemoverPrestador";
            public const string LerOcorrencias = "LerOcorrencias";
            public const string LerBaixasRealizadas = "LerBaixasRealizadas";
        }


        static readonly ActionParamsClass_Index s_params_Index = new ActionParamsClass_Index();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Index IndexParams { get { return s_params_Index; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Index
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Novo s_params_Novo = new ActionParamsClass_Novo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Novo NovoParams { get { return s_params_Novo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Novo
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Editar s_params_Editar = new ActionParamsClass_Editar();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Editar EditarParams { get { return s_params_Editar; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Editar
        {
            public readonly string id = "id";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_Excluir s_params_Excluir = new ActionParamsClass_Excluir();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Excluir ExcluirParams { get { return s_params_Excluir; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Excluir
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_Baixa s_params_Baixa = new ActionParamsClass_Baixa();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Baixa BaixaParams { get { return s_params_Baixa; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Baixa
        {
            public readonly string id = "id";
            public readonly string chequeRecebido = "chequeRecebido";
            public readonly string model = "model";
            public readonly string meioPagamentoId = "meioPagamentoId";
            public readonly string valorRecebimentoChequeRecebido = "valorRecebimentoChequeRecebido";
        }
        static readonly ActionParamsClass_Devolucao s_params_Devolucao = new ActionParamsClass_Devolucao();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Devolucao DevolucaoParams { get { return s_params_Devolucao; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Devolucao
        {
            public readonly string id = "id";
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_ExcluirBaixa s_params_ExcluirBaixa = new ActionParamsClass_ExcluirBaixa();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ExcluirBaixa ExcluirBaixaParams { get { return s_params_ExcluirBaixa; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ExcluirBaixa
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_LerFuncionarios s_params_LerFuncionarios = new ActionParamsClass_LerFuncionarios();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LerFuncionarios LerFuncionariosParams { get { return s_params_LerFuncionarios; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LerFuncionarios
        {
            public readonly string request = "request";
        }
        static readonly ActionParamsClass_AdicionarFuncionario s_params_AdicionarFuncionario = new ActionParamsClass_AdicionarFuncionario();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AdicionarFuncionario AdicionarFuncionarioParams { get { return s_params_AdicionarFuncionario; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AdicionarFuncionario
        {
            public readonly string codigo = "codigo";
        }
        static readonly ActionParamsClass_RemoverFuncionario s_params_RemoverFuncionario = new ActionParamsClass_RemoverFuncionario();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RemoverFuncionario RemoverFuncionarioParams { get { return s_params_RemoverFuncionario; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RemoverFuncionario
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_LerPrestadores s_params_LerPrestadores = new ActionParamsClass_LerPrestadores();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LerPrestadores LerPrestadoresParams { get { return s_params_LerPrestadores; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LerPrestadores
        {
            public readonly string request = "request";
        }
        static readonly ActionParamsClass_AdicionarPrestador s_params_AdicionarPrestador = new ActionParamsClass_AdicionarPrestador();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AdicionarPrestador AdicionarPrestadorParams { get { return s_params_AdicionarPrestador; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AdicionarPrestador
        {
            public readonly string codigo = "codigo";
        }
        static readonly ActionParamsClass_RemoverPrestador s_params_RemoverPrestador = new ActionParamsClass_RemoverPrestador();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_RemoverPrestador RemoverPrestadorParams { get { return s_params_RemoverPrestador; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_RemoverPrestador
        {
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_LerOcorrencias s_params_LerOcorrencias = new ActionParamsClass_LerOcorrencias();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LerOcorrencias LerOcorrenciasParams { get { return s_params_LerOcorrencias; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LerOcorrencias
        {
            public readonly string request = "request";
            public readonly string id = "id";
        }
        static readonly ActionParamsClass_LerBaixasRealizadas s_params_LerBaixasRealizadas = new ActionParamsClass_LerBaixasRealizadas();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LerBaixasRealizadas LerBaixasRealizadasParams { get { return s_params_LerBaixasRealizadas; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LerBaixasRealizadas
        {
            public readonly string request = "request";
            public readonly string id = "id";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _NovoOuEditar = "_NovoOuEditar";
                public readonly string Baixa = "Baixa";
                public readonly string Editar = "Editar";
                public readonly string Index = "Index";
                public readonly string Novo = "Novo";
            }
            public readonly string _NovoOuEditar = "~/Areas/Financeiro/Views/ChequeRecebido/_NovoOuEditar.cshtml";
            public readonly string Baixa = "~/Areas/Financeiro/Views/ChequeRecebido/Baixa.cshtml";
            public readonly string Editar = "~/Areas/Financeiro/Views/ChequeRecebido/Editar.cshtml";
            public readonly string Index = "~/Areas/Financeiro/Views/ChequeRecebido/Index.cshtml";
            public readonly string Novo = "~/Areas/Financeiro/Views/ChequeRecebido/Novo.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ChequeRecebidoController : Fashion.ERP.Web.Areas.Financeiro.Controllers.ChequeRecebidoController
    {
        public T4MVC_ChequeRecebidoController() : base(Dummy.Instance) { }

        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Index()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            IndexOverride(callInfo);
            return callInfo;
        }

        partial void IndexOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Fashion.ERP.Web.Areas.Financeiro.Models.PesquisaChequeRecebidoModel model);

        public override System.Web.Mvc.ActionResult Index(Fashion.ERP.Web.Areas.Financeiro.Models.PesquisaChequeRecebidoModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Index);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            IndexOverride(callInfo, model);
            return callInfo;
        }

        partial void NovoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult Novo()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Novo);
            NovoOverride(callInfo);
            return callInfo;
        }

        partial void NovoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Fashion.ERP.Web.Areas.Financeiro.Models.ChequeRecebidoModel model);

        public override System.Web.Mvc.ActionResult Novo(Fashion.ERP.Web.Areas.Financeiro.Models.ChequeRecebidoModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Novo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            NovoOverride(callInfo, model);
            return callInfo;
        }

        partial void EditarOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long id);

        public override System.Web.Mvc.ActionResult Editar(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Editar);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            EditarOverride(callInfo, id);
            return callInfo;
        }

        partial void EditarOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Fashion.ERP.Web.Areas.Financeiro.Models.ChequeRecebidoModel model);

        public override System.Web.Mvc.ActionResult Editar(Fashion.ERP.Web.Areas.Financeiro.Models.ChequeRecebidoModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Editar);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            EditarOverride(callInfo, model);
            return callInfo;
        }

        partial void ExcluirOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long? id);

        public override System.Web.Mvc.ActionResult Excluir(long? id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Excluir);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ExcluirOverride(callInfo, id);
            return callInfo;
        }

        partial void BaixaOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long? id, long? chequeRecebido);

        public override System.Web.Mvc.ActionResult Baixa(long? id, long? chequeRecebido)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Baixa);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "chequeRecebido", chequeRecebido);
            BaixaOverride(callInfo, id, chequeRecebido);
            return callInfo;
        }

        partial void BaixaOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Fashion.ERP.Web.Areas.Financeiro.Models.BaixaChequeRecebidoModel model, long[] meioPagamentoId, double[] valorRecebimentoChequeRecebido);

        public override System.Web.Mvc.ActionResult Baixa(Fashion.ERP.Web.Areas.Financeiro.Models.BaixaChequeRecebidoModel model, long[] meioPagamentoId, double[] valorRecebimentoChequeRecebido)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Baixa);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "meioPagamentoId", meioPagamentoId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "valorRecebimentoChequeRecebido", valorRecebimentoChequeRecebido);
            BaixaOverride(callInfo, model, meioPagamentoId, valorRecebimentoChequeRecebido);
            return callInfo;
        }

        partial void DevolucaoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long? id);

        public override System.Web.Mvc.ActionResult Devolucao(long? id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Devolucao);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            DevolucaoOverride(callInfo, id);
            return callInfo;
        }

        partial void DevolucaoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Fashion.ERP.Web.Areas.Financeiro.Models.DevolucaoChequeRecebidoModel model);

        public override System.Web.Mvc.ActionResult Devolucao(Fashion.ERP.Web.Areas.Financeiro.Models.DevolucaoChequeRecebidoModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Devolucao);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            DevolucaoOverride(callInfo, model);
            return callInfo;
        }

        partial void ExcluirBaixaOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long id);

        public override System.Web.Mvc.ActionResult ExcluirBaixa(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ExcluirBaixa);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            ExcluirBaixaOverride(callInfo, id);
            return callInfo;
        }

        partial void LerFuncionariosOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Kendo.Mvc.UI.DataSourceRequest request);

        public override System.Web.Mvc.ActionResult LerFuncionarios(Kendo.Mvc.UI.DataSourceRequest request)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LerFuncionarios);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "request", request);
            LerFuncionariosOverride(callInfo, request);
            return callInfo;
        }

        partial void AdicionarFuncionarioOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long codigo);

        public override System.Web.Mvc.ActionResult AdicionarFuncionario(long codigo)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AdicionarFuncionario);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "codigo", codigo);
            AdicionarFuncionarioOverride(callInfo, codigo);
            return callInfo;
        }

        partial void RemoverFuncionarioOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long id);

        public override System.Web.Mvc.ActionResult RemoverFuncionario(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RemoverFuncionario);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            RemoverFuncionarioOverride(callInfo, id);
            return callInfo;
        }

        partial void LerPrestadoresOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Kendo.Mvc.UI.DataSourceRequest request);

        public override System.Web.Mvc.ActionResult LerPrestadores(Kendo.Mvc.UI.DataSourceRequest request)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LerPrestadores);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "request", request);
            LerPrestadoresOverride(callInfo, request);
            return callInfo;
        }

        partial void AdicionarPrestadorOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long codigo);

        public override System.Web.Mvc.ActionResult AdicionarPrestador(long codigo)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.AdicionarPrestador);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "codigo", codigo);
            AdicionarPrestadorOverride(callInfo, codigo);
            return callInfo;
        }

        partial void RemoverPrestadorOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, long id);

        public override System.Web.Mvc.ActionResult RemoverPrestador(long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.RemoverPrestador);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            RemoverPrestadorOverride(callInfo, id);
            return callInfo;
        }

        partial void LerOcorrenciasOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Kendo.Mvc.UI.DataSourceRequest request, long id);

        public override System.Web.Mvc.ActionResult LerOcorrencias(Kendo.Mvc.UI.DataSourceRequest request, long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LerOcorrencias);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "request", request);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            LerOcorrenciasOverride(callInfo, request, id);
            return callInfo;
        }

        partial void LerBaixasRealizadasOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, Kendo.Mvc.UI.DataSourceRequest request, long id);

        public override System.Web.Mvc.ActionResult LerBaixasRealizadas(Kendo.Mvc.UI.DataSourceRequest request, long id)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LerBaixasRealizadas);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "request", request);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "id", id);
            LerBaixasRealizadasOverride(callInfo, request, id);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
