// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Fashion.ERP.Web.Areas.Producao.Controllers
{
    public partial class RelatorioMateriaisProgramacaoProducaoController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RelatorioMateriaisProgramacaoProducaoController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public RelatorioMateriaisProgramacaoProducaoController Actions { get { return MVC.Producao.RelatorioMateriaisProgramacaoProducao; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Producao";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "RelatorioMateriaisProgramacaoProducao";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "RelatorioMateriaisProgramacaoProducao";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string MateriaisProgramacaoProducao = "MateriaisProgramacaoProducao";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string MateriaisProgramacaoProducao = "MateriaisProgramacaoProducao";
        }


        static readonly ActionParamsClass_MateriaisProgramacaoProducao s_params_MateriaisProgramacaoProducao = new ActionParamsClass_MateriaisProgramacaoProducao();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_MateriaisProgramacaoProducao MateriaisProgramacaoProducaoParams { get { return s_params_MateriaisProgramacaoProducao; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_MateriaisProgramacaoProducao
        {
            public readonly string model = "model";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string MateriaisProgramacaoProducao = "MateriaisProgramacaoProducao";
            }
            public readonly string MateriaisProgramacaoProducao = "~/Areas/Producao/Views/RelatorioMateriaisProgramacaoProducao/MateriaisProgramacaoProducao.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_RelatorioMateriaisProgramacaoProducaoController : Fashion.ERP.Web.Areas.Producao.Controllers.RelatorioMateriaisProgramacaoProducaoController
    {
        public T4MVC_RelatorioMateriaisProgramacaoProducaoController() : base(Dummy.Instance) { }

        partial void MateriaisProgramacaoProducaoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult MateriaisProgramacaoProducao()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.MateriaisProgramacaoProducao);
            MateriaisProgramacaoProducaoOverride(callInfo);
            return callInfo;
        }

        partial void MateriaisProgramacaoProducaoOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, Fashion.ERP.Web.Areas.Producao.Models.MateriaisProgramacaoProducaoModel model);

        public override System.Web.Mvc.JsonResult MateriaisProgramacaoProducao(Fashion.ERP.Web.Areas.Producao.Models.MateriaisProgramacaoProducaoModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.MateriaisProgramacaoProducao);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            MateriaisProgramacaoProducaoOverride(callInfo, model);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
