// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace Fashion.ERP.Web.Areas.Producao.Controllers
{
    public partial class RelatorioEstimativaConsumoProgramadoController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RelatorioEstimativaConsumoProgramadoController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public RelatorioEstimativaConsumoProgramadoController Actions { get { return MVC.Producao.RelatorioEstimativaConsumoProgramado; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Producao";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "RelatorioEstimativaConsumoProgramado";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "RelatorioEstimativaConsumoProgramado";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string EstimativaConsumoProgramado = "EstimativaConsumoProgramado";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string EstimativaConsumoProgramado = "EstimativaConsumoProgramado";
        }


        static readonly ActionParamsClass_EstimativaConsumoProgramado s_params_EstimativaConsumoProgramado = new ActionParamsClass_EstimativaConsumoProgramado();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EstimativaConsumoProgramado EstimativaConsumoProgramadoParams { get { return s_params_EstimativaConsumoProgramado; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EstimativaConsumoProgramado
        {
            public readonly string model = "model";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string EstimativaConsumoProgramado = "EstimativaConsumoProgramado";
            }
            public readonly string EstimativaConsumoProgramado = "~/Areas/Producao/Views/RelatorioEstimativaConsumoProgramado/EstimativaConsumoProgramado.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_RelatorioEstimativaConsumoProgramadoController : Fashion.ERP.Web.Areas.Producao.Controllers.RelatorioEstimativaConsumoProgramadoController
    {
        public T4MVC_RelatorioEstimativaConsumoProgramadoController() : base(Dummy.Instance) { }

        partial void EstimativaConsumoProgramadoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        public override System.Web.Mvc.ActionResult EstimativaConsumoProgramado()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EstimativaConsumoProgramado);
            EstimativaConsumoProgramadoOverride(callInfo);
            return callInfo;
        }

        partial void EstimativaConsumoProgramadoOverride(T4MVC_System_Web_Mvc_JsonResult callInfo, Fashion.ERP.Web.Areas.Producao.Models.EstimativaConsumoProgramadoModel model);

        public override System.Web.Mvc.JsonResult EstimativaConsumoProgramado(Fashion.ERP.Web.Areas.Producao.Models.EstimativaConsumoProgramadoModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.EstimativaConsumoProgramado);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            EstimativaConsumoProgramadoOverride(callInfo, model);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
