INSERT INTO generofiscal (id, codigo, descricao) VALUES (1, '0' ,'Serviço');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (2, '1' ,'Animais vivos');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (3, '2' ,'Carnes e miudezas, comestíveis');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (4, '3' ,'Peixes e crustáceos, moluscos e os outros invertebrados aquáticos');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (5, '4' ,'Leite e laticínios; ovos de aves; mel natural; produtos comestíveis de origem animal, não especificados nem compreendidos em outros Capítulos da TIPI');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (6, '5' ,'Outros produtos de origem animal, não especificados nem compreendidos em outros Capítulos da TIPI');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (7, '6' ,'Plantas vivas e produtos de floricultura');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (8, '7' ,'Produtos hortícolas, plantas, raízes e tubérculos, comestíveis');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (9, '8' ,'Frutas; cascas de cítricos e de melões');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (10, '9' ,'Café, chá, mate e especiarias');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (11, '10' ,'Cereais');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (12, '11' ,'Produtos da indústria de moagem; malte; amidos e féculas; inulina; glúten de trigo');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (13, '12' ,'Sementes e frutos oleaginosos; grãos, sementes e frutos diversos; plantas industriais ou medicinais; palha e forragem');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (14, '13' ,'Gomas, resinas e outros sucos e extratos vegetais');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (15, '14' ,'Matérias para entrançar e outros produtos de origem vegetal, não especificadas nem compreendidas em outros Capítulos da NCM');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (16, '15' ,'Gorduras e óleos animais ou vegetais; produtos da sua dissociação; gorduras alimentares elaboradas; ceras de origem animal ou vegetal');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (17, '16' ,'Preparações de carne, de peixes ou de crustáceos, de moluscos ou de outros invertebrados aquáticos');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (18, '17' ,'Açúcares e produtos de confeitaria');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (19, '18' ,'Cacau e suas preparações');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (20, '19' ,'Preparações à base de cereais, farinhas, amidos, féculas ou de leite; produtos de pastelaria');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (21, '20' ,'Preparações de produtos hortícolas, de frutas ou de outras partes de plantas');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (22, '21' ,'Preparações alimentícias diversas');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (23, '22' ,'Bebidas, líquidos alcoólicos e vinagres');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (24, '23' ,'Resíduos e desperdícios das indústrias alimentares; alimentos preparados para animais');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (25, '24' ,'Fumo (tabaco) e seus sucedâneos, manufaturados');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (26, '25' ,'Sal; enxofre; terras e pedras; gesso, cal e cimento');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (27, '26' ,'Minérios, escórias e cinzas');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (28, '27' ,'Combustíveis minerais, óleos minerais e produtos de sua destilação; matérias betuminosas; ceras minerais');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (29, '28' ,'Produtos químicos inorgânicos; compostos inorgânicos ou orgânicos de metais preciosos, de elementos radioativos, de metais das terras raras ou de isótopos');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (30, '29' ,'Produtos químicos orgânicos');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (31, '30' ,'Produtos farmacêuticos');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (32, '31' ,'Adubos ou fertilizantes');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (33, '32' ,'Extratos tanantes e tintoriais; taninos e seus derivados; pigmentos e outras matérias corantes, tintas e vernizes, mástiques; tintas de escrever');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (34, '33' ,'Óleos essenciais e resinóides; produtos de perfumaria ou de toucador preparados e preparações cosméticas');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (35, '35' ,'Matérias albuminóides; produtos à base de amidos ou de féculas modificados; colas; enzimas');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (36, '36' ,'Pólvoras e explosivos; artigos de pirotecnia; fósforos; ligas pirofóricas; matérias inflamáveis');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (37, '37' ,'Produtos para fotografia e cinematografia');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (38, '38' ,'Produtos diversos das indústrias químicas');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (39, '39' ,'Plásticos e suas obras');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (40, '40' ,'Borracha e suas obras');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (41, '41' ,'Peles, exceto a peleteria (peles com pêlo*), e couros');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (42, '42' ,'Obras de couro; artigos de correeiro ou de seleiro; artigos de viagem, bolsas e artefatos semelhantes; obras de tripa');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (43, '43' ,'Peleteria (peles com pêlo*) e suas obras; peleteria (peles com pêlo*) artificial');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (44, '44' ,'Madeira, carvão vegetal e obras de madeira');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (45, '45' ,'Cortiça e suas obras');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (46, '46' ,'Obras de espartaria ou de cestaria');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (47, '47' ,'Pastas de madeira ou de outras matérias fibrosas celulósicas; papel ou cartão de reciclar (desperdícios e aparas)');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (48, '48' ,'Papel e cartão; obras de pasta de celulose, de papel ou de cartão');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (49, '49' ,'Livros, jornais, gravuras e outros produtos das indústrias gráficas; textos manuscritos ou datilografados, planos e plantas');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (50, '50' ,'Seda');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (51, '51' ,'Lã e pêlos finos ou grosseiros; fios e tecidos de crina');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (52, '52' ,'Algodão');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (53, '53' ,'Outras fibras têxteis vegetais; fios de papel e tecido de fios de papel');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (54, '54' ,'Filamentos sintéticos ou artificiais');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (55, '55' ,'Fibras sintéticas ou artificiais, descontínuas');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (56, '56' ,'Pastas ("ouates"), feltros e falsos tecidos; fios especiais; cordéis, cordas e cabos; artigos de cordoaria');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (57, '57' ,'Tapetes e outros revestimentos para pavimentos, de matérias têxteis');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (58, '58' ,'Tecidos especiais; tecidos tufados; rendas; tapeçarias; passamanarias; bordados');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (59, '59' ,'Tecidos impregnados, revestidos, recobertos ou estratificados; artigos para usos técnicos de matérias têxteis');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (60, '60' ,'Tecidos de malha');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (61, '61' ,'Vestuário e seus acessórios, de malha');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (62, '62' ,'Vestuário e seus acessórios, exceto de malha');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (63, '63' ,'Outros artefatos têxteis confeccionados; sortidos; artefatos de matérias têxteis, calçados, chapéus e artefatos de uso semelhante, usados; trapos');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (64, '64' ,'Calçados, polainas e artefatos semelhantes, e suas partes');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (65, '65' ,'Chapéus e artefatos de uso semelhante, e suas partes');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (66, '66' ,'Guarda-chuvas, sombrinhas, guarda-sóis, bengalas, bengalas-assentos, chicotes, e suas partes');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (67, '67' ,'Penas e penugem preparadas, e suas obras; flores artificiais; obras de cabelo');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (68, '68' ,'Obras de pedra, gesso, cimento, amianto, mica ou de matérias semelhantes');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (69, '69' ,'Produtos cerâmicos');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (70, '70' ,'Vidro e suas obras');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (71, '71' ,'Pérolas naturais ou cultivadas, pedras preciosas ou semipreciosas e semelhantes, metais preciosos, metais folheados ou chapeados de metais preciosos, e suas obras; bijuterias; moedas');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (72, '72' ,'Ferro fundido, ferro e aço');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (73, '73' ,'Obras de ferro fundido, ferro ou aço');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (74, '74' ,'Cobre e suas obras');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (75, '75' ,'Níquel e suas obras');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (76, '76' ,'Alumínio e suas obras');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (77, '77' ,'(Reservado para uma eventual utilização futura no SH)');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (78, '78' ,'Chumbo e suas obras');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (79, '79' ,'Zinco e suas obras');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (80, '80' ,'Estanho e suas obras');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (81, '81' ,'Outros metais comuns; ceramais ("cermets"); obras dessas matérias');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (82, '82' ,'Ferramentas, artefatos de cutelaria e talheres, e suas partes, de metais comuns');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (83, '83' ,'Obras diversas de metais comuns');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (84, '84' ,'Reatores nucleares, caldeiras, máquinas, aparelhos e instrumentos mecânicos, e suas partes');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (85, '85' ,'Máquinas, aparelhos e materiais elétricos, e suas partes; aparelhos de gravação ou de reprodução de som, aparelhos de gravação ou de reprodução de imagens e de som em televisão, e suas partes e acessórios');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (86, '86' ,'Veículos e material para vias férreas ou semelhantes, e suas partes; aparelhos mecânicos (incluídos os eletromecânicos) de sinalização para vias de comunicação');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (87, '87' ,'Veículos automóveis, tratores, ciclos e outros veículos terrestres, suas partes e acessórios');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (88, '88' ,'Aeronaves e aparelhos espaciais, e suas partes');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (89, '89' ,'Embarcações e estruturas flutuantes');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (90, '90' ,'Instrumentos e aparelhos de óptica, fotografia ou cinematografia, medida, controle ou de precisão; instrumentos e aparelhos médico-cirúrgicos; suas partes e acessórios');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (91, '91' ,'Aparelhos de relojoaria e suas partes');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (92, '92' ,'Instrumentos musicais, suas partes e acessórios');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (93, '93' ,'Armas e munições; suas partes e acessórios');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (94, '94' ,'Móveis, mobiliário médico-cirúrgico; colchões; iluminação e construção pré-fabricadas');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (95, '95' ,'Brinquedos, jogos, artigos para divertimento ou para esporte; suas partes e acessórios');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (96, '96' ,'Obras diversas');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (97, '97' ,'Objetos de arte, de coleção e antiguidades');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (98, '98' ,'(Reservado para usos especiais pelas Partes Contratantes)');
INSERT INTO generofiscal (id, codigo, descricao) VALUES (99, '99' ,'Operações especiais (utilizado exclusivamente pelo Brasil para classificar operações especiais na exportação)');
